// Sync Protocol v1 conformance harness.
//
// P1: exercises the REAL shipping library (src/Sync) against the shared test vectors in
// docs/sync-vectors/v1/ -- the same files the Kotlin :core tests consume. The vectors are
// generated by Node (docs/sync-vectors/generate.mjs), so passing here is a genuine
// cross-implementation check: Node produced the bytes, the shipping C# consumes them.
//
// P0's version verified vectors with local helper crypto; those helpers are gone, which
// was always the plan ("when the real SyncPublisher lands in P1, this harness points at
// it instead").

using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using SeekerSvc.Sync;

int passed = 0, failed = 0;
void Check(string name, bool condition, string? detail = null)
{
    if (condition) { passed++; Console.WriteLine($"  PASS  {name}"); }
    else { failed++; Console.WriteLine($"  FAIL  {name}{(detail is null ? "" : $"  -- {detail}")}"); }
}

Console.WriteLine("=== CareerSeeker sync protocol v1 harness ===\n");

var vectorDir = LocateVectorDirectory();
if (vectorDir is null)
{
    Console.WriteLine("  FAIL  vector directory docs/sync-vectors/v1 not found");
    Console.WriteLine("\n=== 0 passed, 1 failed ===");
    return 1;
}
Console.WriteLine($"Vectors: {vectorDir}\n");

// ---------------------------------------------------------------- suite integrity

Console.WriteLine("[ vector suite integrity ]");

var index = JsonNode.Parse(File.ReadAllText(Path.Combine(vectorDir, "index.json")))!.AsObject();
var declared = index["vectors"]!.AsArray();
var activeKeyId = (string)index["active_key_id"]!;

Check("index declares AES-256-GCM", (string?)index["cipher"] == "AES-256-GCM");
Check("index suite matches the shipping suite", (string?)index["suite"] == Protocol.Suite,
    $"index={(string?)index["suite"]} code={Protocol.Suite}");
Check("index envelope limit matches the spec", (int?)index["max_envelope_bytes"] == Protocol.MaxEnvelopeBytes);
Check("index names an active key id for revocation checks", !string.IsNullOrEmpty(activeKeyId));

var onDisk = Directory.GetFiles(vectorDir, "*.json")
    .Select(Path.GetFileNameWithoutExtension)
    .Where(n => n != "index")
    .OrderBy(n => n, StringComparer.Ordinal)
    .ToList();
Check("every declared vector exists on disk",
    declared.Select(v => (string)v!["name"]!).OrderBy(n => n, StringComparer.Ordinal).SequenceEqual(onDisk),
    $"declared {declared.Count}, on disk {onDisk.Count}");

var vectors = onDisk
    .Select(n => JsonNode.Parse(File.ReadAllText(Path.Combine(vectorDir, n + ".json")))!.AsObject())
    .ToList();
var envelopeVectors = vectors.Where(v => (string)v["type"]! == "envelope").ToList();
var pairingVectors = vectors.Where(v => (string)v["type"]! == "pairing").ToList();

Check("suite has envelope and pairing vectors, valid and invalid",
    envelopeVectors.Any(v => (bool)v["valid"]!) && envelopeVectors.Any(v => !(bool)v["valid"]!)
    && pairingVectors.Any(v => (bool)v["valid"]!) && pairingVectors.Any(v => !(bool)v["valid"]!));

// ---------------------------------------------------------------- pairing derivation
//
// Done before the envelope work because the receiver needs the pairing's device key.

Console.WriteLine("\n[ pairing: section-5.2 derivation reproduces every vector value ]");

var pairingBasic = pairingVectors.Single(v => (string)v["name"]! == "pairing-basic");
var expected = pairingBasic["expected"]!.AsObject();
var secret = Convert.FromHexString(ToHex(pairingBasic["secret_b64u"]!));

using var engineKey = ImportEcdh((string)pairingBasic["engine"]!["d_hex"]!, (string)pairingBasic["engine"]!["pub_b64u"]!);
using var phoneKey = ImportEcdh((string)pairingBasic["phone"]!["d_hex"]!, (string)pairingBasic["phone"]!["pub_b64u"]!);
var enginePub = B64u((string)pairingBasic["engine"]!["pub_b64u"]!);
var phonePub = B64u((string)pairingBasic["phone"]!["pub_b64u"]!);
var devicePub = B64u((string)pairingBasic["device_sig"]!["pub_b64u"]!);

var ssEngineSide = PairingCrypto.ComputeSharedSecret(engineKey, phonePub);
var ssPhoneSide = PairingCrypto.ComputeSharedSecret(phoneKey, enginePub);
Check("ECDH shared secret matches the vector (engine side)",
    Convert.ToHexString(ssEngineSide).Equals((string)expected["ss_hex"]!, StringComparison.OrdinalIgnoreCase));
Check("ECDH is symmetric (phone side derives the same secret)",
    ssEngineSide.AsSpan().SequenceEqual(ssPhoneSide));

var keys = PairingCrypto.Derive(new[] { ssEngineSide }, secret);
Check("k_e2p matches", Convert.ToHexString(keys.KeyEngineToPhone).Equals((string)expected["k_e2p_hex"]!, StringComparison.OrdinalIgnoreCase));
Check("k_p2e matches", Convert.ToHexString(keys.KeyPhoneToEngine).Equals((string)expected["k_p2e_hex"]!, StringComparison.OrdinalIgnoreCase));
Check("relay token matches", keys.RelayToken == (string)expected["relay_token_b64u"]!);
Check("6-digit confirm code matches", keys.ConfirmCode == (string)expected["confirm"]!,
    $"derived {keys.ConfirmCode}, vector {(string)expected["confirm"]!}");
Check("provisional bootstrap token matches",
    PairingCrypto.ProvisionalRelayToken(secret) == (string)expected["provisional_token_b64u"]!);

var completion = pairingBasic["completion"]!.AsObject();
Check("completion AAD is reconstructed exactly",
    PairingCrypto.CompletionAad((string)index["pairing_id"]!, (string)pairingBasic["suite"]!, (string)pairingBasic["phone"]!["pub_b64u"]!)
        == (string)completion["aad"]!);

byte[]? completionPayload = null;
try
{
    completionPayload = EnvelopeCodec.Open(keys.KeyPhoneToEngine, B64u((string)completion["nonce_b64u"]!),
        (string)completion["aad"]!, B64u((string)completion["ciphertext_b64u"]!));
}
catch (CryptographicException) { /* fails the next check */ }
Check("completion opens under the derived k_p2e", completionPayload is not null);
Check("device signing key travels inside the completion ciphertext",
    completionPayload is not null
    && (string?)JsonNode.Parse(completionPayload)?["device_sig_pub"] == (string)pairingBasic["device_sig"]!["pub_b64u"]!);

// The MITM vector: relay swaps phone_pub for the attacker's. Deriving from the attacker
// key and opening MUST fail -- phone_pub is bound into the AAD *and* changes the key.
var mitm = pairingVectors.Single(v => (string)v["name"]! == "pairing-mitm-keyswap");
var attackerPub = B64u((string)mitm["phone"]!["pub_b64u"]!);
var mitmKeys = PairingCrypto.Derive(new[] { PairingCrypto.ComputeSharedSecret(engineKey, attackerPub) }, secret);
bool mitmRejected;
try
{
    EnvelopeCodec.Open(mitmKeys.KeyPhoneToEngine, B64u((string)mitm["completion"]!["nonce_b64u"]!),
        (string)mitm["completion"]!["aad"]!, B64u((string)mitm["completion"]!["ciphertext_b64u"]!));
    mitmRejected = false;
}
catch (CryptographicException) { mitmRejected = true; }
Check("pairing-mitm-keyswap: swapped phone_pub cannot decrypt the completion", mitmRejected,
    "a relay that substitutes keys must break the handshake, not hijack it");

// ---------------------------------------------------------------- valid envelope vectors

Console.WriteLine("\n[ valid envelope vectors decrypt and verify through src/Sync ]");

var validEnv = envelopeVectors.Where(v => (bool)v["valid"]!).ToList();
var invalidEnv = envelopeVectors.Where(v => !(bool)v["valid"]!).ToList();

foreach (var v in validEnv)
{
    var name = (string)v["name"]!;
    try
    {
        var text = Encoding.UTF8.GetString(EnvelopeCodec.Open(
            Convert.FromHexString((string)v["key_hex"]!), B64u((string)v["nonce_b64u"]!),
            (string)v["aad"]!, B64u((string)v["ciphertext_b64u"]!)));
        Check($"{name} round-trips", Canonical(JsonNode.Parse(text)) == Canonical(v["plaintext_json"]));
    }
    catch (Exception ex)
    {
        Check($"{name} round-trips", false, ex.GetType().Name);
    }

    if (v["envelope_json"]!["sig"] is not null)
    {
        var ciphertext = B64u((string)v["ciphertext_b64u"]!);
        var input = DeviceSignature.SigInput((string)v["aad"]!, (string)v["nonce_b64u"]!, ciphertext);
        Check($"{name} sig_input is reconstructed exactly", input == (string)v["sig_input"]!);
        Check($"{name} signature verifies under the device key",
            DeviceSignature.Verify(B64u((string)v["device_sig_pub_b64u"]!), input, B64u((string)v["envelope_json"]!["sig"]!)));
    }
}

Console.WriteLine("\n[ header fields are bound into the AEAD ]");

foreach (var v in validEnv)
{
    var aad = (string)v["aad"]!;
    var tampered = aad.Contains("dir=e2p") ? aad.Replace("dir=e2p", "dir=p2e") : aad.Replace("dir=p2e", "dir=e2p");
    bool rejected;
    try
    {
        EnvelopeCodec.Open(Convert.FromHexString((string)v["key_hex"]!), B64u((string)v["nonce_b64u"]!),
            tampered, B64u((string)v["ciphertext_b64u"]!));
        rejected = false;
    }
    catch (CryptographicException) { rejected = true; }
    Check($"{(string)v["name"]!} rejects a tampered AAD", rejected);
}

// ---------------------------------------------------------------- receiver state machine
//
// The REAL receiver (src/Sync EnvelopeReceiver) classifies every envelope vector. Valid
// vectors are fed first in sequence order -- the replay vector's notes require it -- and
// the receiver is constructed with the PAIRING's device key, which is what makes
// sig-by-revoked-key meaningful: that envelope verifies under the key it *names*, and
// must still be rejected because it is not the pairing's key.

Console.WriteLine("\n[ the shipping receiver classifies every vector correctly ]");

var receiver = new EnvelopeReceiver(activeKeyId, devicePub);
byte[] KeyFor(string dir) => dir == "e2p"
    ? Convert.FromHexString("a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90")
    : Convert.FromHexString("0f1e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0");

// Vectors are fed as WIRE TEXT through the strict §3 parser, not field-by-field. That is the
// point of routing them this way: the old ToReceived read the nine names it wanted and dropped
// everything else, so a vector carrying a tenth field was accepted here and rejected on the
// phone, and no vector could express the difference (B-6 / PQ-A2-3).
ReceiveResult ReceiveWire(JsonObject envelopeJson)
{
    var parsed = EnvelopeJson.Parse(envelopeJson.ToJsonString());
    return parsed.Error is { } err
        ? new ReceiveResult(err, null, null)
        : receiver.Receive(parsed.Envelope!, KeyFor);
}

foreach (var v in validEnv.OrderBy(v => (long)v["envelope_json"]!["seq"]!))
{
    var result = ReceiveWire(v["envelope_json"]!.AsObject());
    Check($"receiver accepts {(string)v["name"]!}", result.Accepted, result.Error?.ToWire());
}

foreach (var v in invalidEnv)
{
    var name = (string)v["name"]!;
    var expectedCode = (string)v["expect_error"]!;

    ReceiveResult result;
    if (v["envelope_json"] is null)
    {
        // invalid-oversized ships a synth length instead of a megabyte of literal 'A's.
        var synth = (int)v["synth_ciphertext_len"]!;
        var big = new ReceivedEnvelope(1, "p_7Fq2mXk9LtVbN3wR", "e2p", 999, "2026-06-11T14:02:11Z",
            activeKeyId, Base64Url.Encode(new byte[Protocol.NonceBytes]), Base64Url.Encode(new byte[synth]), null);
        result = receiver.Receive(big, KeyFor);
    }
    else
    {
        result = ReceiveWire(v["envelope_json"]!.AsObject());
    }

    Check($"{name} -> {expectedCode}", result.Error?.ToWire() == expectedCode,
        $"got {result.Error?.ToWire() ?? "accepted"}");
}

Check("rejections never advanced the sequence tracker",
    receiver.HighestAccepted("e2p") == 4 && receiver.HighestAccepted("p2e") == 1,
    $"e2p={receiver.HighestAccepted("e2p")} p2e={receiver.HighestAccepted("p2e")}");

// ---------------------------------------------------------------- strict section-3 parser
//
// invalid-unknown-field pins the rule end-to-end through the vectors. These pin the parser
// directly, and cover the cases no vector file can carry: a vector IS json, so it cannot
// express "the wire bytes were not JSON at all" or "the root was not an object", and
// index.json gives each vector exactly one expect_error, so a case whose whole interest is
// *which check fired first* has nowhere to live in the shared suite.

Console.WriteLine("\n[ the strict section-3 wire parser ]");

var goodWire = envelopeVectors.Single(v => (string)v["name"]! == "delta-basic")["envelope_json"]!.AsObject();
string WireWith(Action<JsonObject> edit)
{
    var o = JsonNode.Parse(goodWire.ToJsonString())!.AsObject();
    edit(o);
    return o.ToJsonString();
}

Check("parser accepts an envelope carrying exactly the nine section-3 fields",
    EnvelopeJson.Parse(goodWire.ToJsonString()).Ok);

Check("an unknown top-level field is rejected as decrypt_failed",
    EnvelopeJson.Parse(WireWith(o => o["next_seq"] = 99)).Error == SyncError.DecryptFailed);

// PQ-ER-1, pinned rather than argued: the unknown-field check runs BEFORE the version check,
// so a v2 sender that also adds a field cannot learn that the version is the problem. The
// pair of assertions is the point -- the second shows the first is about the field, not the
// version, which a single assertion could not distinguish.
Check("unknown-field rejection precedes the version check (PQ-ER-1)",
    EnvelopeJson.Parse(WireWith(o => { o["v"] = 2; o["next_seq"] = 99; })).Error == SyncError.DecryptFailed);
Check("the same envelope WITHOUT the extra field is told version_unsupported instead",
    new EnvelopeReceiver(activeKeyId, devicePub)
        .Receive(EnvelopeJson.Parse(WireWith(o => o["v"] = 2)).Envelope!, KeyFor)
        .Error == SyncError.VersionUnsupported);

// A present-but-non-string sig must not silently degrade into "unsigned": that would turn a
// malformed signature into a missing one, and the two are reported by different checks at
// different times (decrypt_failed before decryption, bad_signature after).
Check("a present-but-non-string sig is rejected, not read as unsigned",
    EnvelopeJson.Parse(WireWith(o => o["sig"] = 42)).Error == SyncError.DecryptFailed);
Check("an explicit JSON null sig parses as absent",
    EnvelopeJson.Parse(WireWith(o => o["sig"] = null)) is { Ok: true, Envelope.Sig: null });

Check("seq as a quoted string is rejected (types are not coerced)",
    EnvelopeJson.Parse(WireWith(o => o["seq"] = "12")).Error == SyncError.DecryptFailed);
Check("v as a quoted string is rejected (types are not coerced)",
    EnvelopeJson.Parse(WireWith(o => o["v"] = "1")).Error == SyncError.DecryptFailed);
Check("a malformed pairing id is rejected before it can reach the AAD",
    EnvelopeJson.Parse(WireWith(o => o["pairing"] = "not-a-pairing-id")).Error == SyncError.DecryptFailed);

Check("a JSON root that is not an object is rejected",
    EnvelopeJson.Parse("[1,2,3]").Error == SyncError.DecryptFailed);
Check("wire bytes that are not JSON at all are rejected",
    EnvelopeJson.Parse("{not json").Error == SyncError.DecryptFailed);

// ---------------------------------------------------------------- pairing manager
//
// Drives the engine's PairingManager through a full handshake using the pairing-basic
// vector's fixed keys, so the manager's orchestration (invite, provisional token,
// completion verification, secret burn) is checked against the same derivations the
// cross-repo vectors pin.

Console.WriteLine("\n[ engine PairingManager completes the handshake ]");

{
    var engineD = (string)pairingBasic["engine"]!["d_hex"]!;
    using var fixedEngineKey = ImportEcdh(engineD, (string)pairingBasic["engine"]!["pub_b64u"]!);
    var pairingId = (string)index["pairing_id"]!;
    using var mgr = new PairingManager("https://relay.careerseeker.app",
        engineKey: fixedEngineKey, oneTimeSecret: secret, pairingId: pairingId);

    var invite = mgr.CreateInvite();
    Check("invite carries the suite and engine pubkey",
        invite.Suite == Protocol.Suite && invite.EnginePub == (string)pairingBasic["engine"]!["pub_b64u"]!);
    Check("provisional token matches the derived value",
        mgr.ProvisionalRelayToken() == (string)expected["provisional_token_b64u"]!);

    // The phone's completion, reconstructed from the vector.
    var completionJson = JsonSerializer.Serialize(new
    {
        suite = Protocol.Suite,
        phone_pub = (string)pairingBasic["phone"]!["pub_b64u"]!,
        nonce = (string)completion["nonce_b64u"]!,
        ciphertext = (string)completion["ciphertext_b64u"]!,
    });

    var paired = mgr.CompletePairing(completionJson, out var err);
    Check("completion succeeds", paired is not null, err);
    Check("paired confirm code matches the vector", paired?.ConfirmCode == (string)expected["confirm"]!);
    Check("paired relay token matches the vector", paired?.RelayToken == (string)expected["relay_token_b64u"]!);
    Check("paired device key equals the one inside the completion",
        paired is not null && Base64Url.Encode(paired.DeviceSigPub) == (string)pairingBasic["device_sig"]!["pub_b64u"]!);

    // Single-use secret: a second completion, even the same valid one, is refused.
    var replay = mgr.CompletePairing(completionJson, out var replayErr);
    Check("secret is single-use (second completion refused)", replay is null, replayErr);

    // A key-swapped completion (the MITM vector) does not decrypt.
    var mitmJson = JsonSerializer.Serialize(new
    {
        suite = Protocol.Suite,
        phone_pub = (string)mitm["phone"]!["pub_b64u"]!,
        nonce = (string)mitm["completion"]!["nonce_b64u"]!,
        ciphertext = (string)mitm["completion"]!["ciphertext_b64u"]!,
    });
    using var mgr2 = new PairingManager("https://relay.careerseeker.app",
        engineKey: ImportEcdh(engineD, (string)pairingBasic["engine"]!["pub_b64u"]!),
        oneTimeSecret: secret, pairingId: pairingId);
    var mitmResult = mgr2.CompletePairing(mitmJson, out _);
    Check("PairingManager rejects a key-swapped completion", mitmResult is null);
}

// ---------------------------------------------------------------- P2 publisher payloads
//
// The engine->phone snapshot/delta/heartbeat builders (SyncPayloads) seal through the
// codec, decode back to their kind, pass the receiver, and -- the load-bearing check --
// carry only structured dashboard fields, never a raw posting body (the untrusted-text
// invariant). Sealed with the pairing-basic k_e2p so it rides the same proven key.

Console.WriteLine("\n[ P2 snapshot/delta/heartbeat payloads ]");

{
    var kE2p = Convert.FromHexString((string)expected["k_e2p_hex"]!);
    var counters = new Counters(Discovered: 3, Acted: 1, Drafted: 1, Blocked: 0, Rejected: 1, Errors: 0, Cycles: 7);
    var apps = new[] { new AppSummary("app_01H8XK", "READY", "Northwind Labs", "Senior Platform Engineer", 82) };
    var jobs = new[] { new JobSummary("job_1", "Northwind Labs", "Senior Platform Engineer", Repost: false, InjectionFlag: false) };

    string SealAndKind(byte[] plaintext, long seq)
    {
        var header = new EnvelopeHeader(1, (string)index["pairing_id"]!, "e2p", seq, "2026-07-23T12:00:00Z", activeKeyId);
        var nonce = System.Security.Cryptography.RandomNumberGenerator.GetBytes(12);
        var ct = EnvelopeCodec.Seal(kE2p, nonce, header.Aad(), plaintext);
        var env = new ReceivedEnvelope(1, header.Pairing, "e2p", seq, header.Ts, activeKeyId,
            Base64Url.Encode(nonce), Base64Url.Encode(ct), null);
        var r = new EnvelopeReceiver(activeKeyId).Receive(env, _ => kE2p);
        return r.Accepted ? r.Kind! : $"REJECTED:{r.Error?.ToWire()}";
    }

    var snap = SyncPayloads.Snapshot(counters, apps, jobs);
    Check("snapshot seals, decodes, and is accepted as kind=snapshot", SealAndKind(snap, 1) == "snapshot");
    Check("delta is accepted as kind=delta", SealAndKind(SyncPayloads.Delta(1, counters, apps, jobs), 2) == "delta");
    Check("heartbeat is accepted as kind=heartbeat", SealAndKind(SyncPayloads.Heartbeat("2026-07-23T12:00:00Z", 7, counters), 3) == "heartbeat");

    var snapText = Encoding.UTF8.GetString(snap);
    Check("snapshot carries the live counters", snapText.Contains("\"drafted\":1") && snapText.Contains("\"cycles\":7"));
    Check("snapshot carries application summary fields", snapText.Contains("\"score\":82") && snapText.Contains("Senior Platform Engineer"));
    // Outcome (P4 §2.5) is nullable on the wire: present when set, omitted (absent => null) otherwise.
    var withOutcome = Encoding.UTF8.GetString(SyncPayloads.Snapshot(counters,
        new[] { new AppSummary("app_1", "APPLIED", "Acme", "Engineer", 80, "interview") }, jobs));
    Check("snapshot carries a set outcome", withOutcome.Contains("\"outcome\":\"interview\""));
    Check("snapshot omits outcome when unset (absent => null on the phone)", !snapText.Contains("outcome"));
    // The untrusted-text invariant, asserted: no field name that would carry a raw posting body.
    Check("snapshot carries NO raw posting body (untrusted-text rule)",
        !snapText.Contains("jd_path") && !snapText.Contains("description") && !snapText.Contains("posting_body") && !snapText.Contains("\"body\":\""),
        "a P2 dashboard payload must never ship an interpolable posting body");

    // evidence: the audit-chain verdict + event metadata for the Evidence screen.
    var events = new[] { new EvidenceEvent(1, "2026-07-23T09:00:11Z", "engine", "scout_ingest", "scout", "b41f") };
    var evidence = SyncPayloads.Evidence(auditOk: true, firstBrokenSeq: null, eventCount: 42, events: events);
    Check("evidence seals, decodes, and is accepted as kind=evidence", SealAndKind(evidence, 4) == "evidence");
    var evText = Encoding.UTF8.GetString(evidence);
    Check("evidence carries the audit verdict and event metadata",
        evText.Contains("\"audit_ok\":true") && evText.Contains("\"event_count\":42") && evText.Contains("\"entity_id\":\"b41f\""));
    Check("evidence omits first_broken_seq when the chain is intact", !evText.Contains("first_broken_seq"));
    Check("evidence carries NO raw event payload body (metadata only)",
        !evText.Contains("payload") && !evText.Contains("\"body\":\"") && !evText.Contains("description"));
}

// ---------------------------------------------------------------- P2 publisher
//
// SyncPublisher is the shipping seal-and-push mechanism: it assigns the monotonic e2p seq the
// relay enforces, seals each SyncPayloads plaintext with k_e2p, and hands the wire envelope to a
// sink. Here the sink is a fake that records only successful pushes, so sequencing and the
// gap-on-failure rule are checked offline; the receiver then opens every pushed envelope, proving
// the bytes are the same shape the phone parses. Sealed with the pairing-basic k_e2p.

Console.WriteLine("\n[ SyncPublisher seals, sequences, and pushes e2p envelopes ]");

{
    var kE2p = Convert.FromHexString((string)expected["k_e2p_hex"]!);
    var pairingId = (string)index["pairing_id"]!;
    var counters = new Counters(Discovered: 3, Acted: 1, Drafted: 1, Blocked: 0, Rejected: 1, Errors: 0, Cycles: 7);
    var apps = new[] { new AppSummary("app_01H8XK", "READY", "Northwind Labs", "Senior Platform Engineer", 82) };
    var jobs = new[] { new JobSummary("job_1", "Northwind Labs", "Senior Platform Engineer", Repost: false, InjectionFlag: false) };

    var pushed = new List<string>();
    var sinkOk = true;
    // The fake relay records only what it accepts, mirroring a real push: a failed push stores nothing,
    // so the phone never sees that seq and the burned number becomes a legitimate gap.
    Func<string, CancellationToken, Task<bool>> sink = (env, _) => { if (sinkOk) pushed.Add(env); return Task.FromResult(sinkOk); };

    // Deterministic clock and nonce keep the harness reproducible; the nonce still advances so no two
    // envelopes reuse one (nonce reuse under a single GCM key is catastrophic).
    var nonceCounter = 0;
    Func<byte[]> nonces = () => { var n = new byte[Protocol.NonceBytes]; n[0] = (byte)(++nonceCounter); return n; };
    var publisher = new SyncPublisher(kE2p, pairingId, activeKeyId, sink,
        clock: () => new DateTimeOffset(2026, 7, 23, 12, 0, 0, TimeSpan.Zero), nonceSource: nonces);

    Check("publisher starts at seq 0", publisher.HighestSeq == 0);
    Check("snapshot push succeeds and advances to seq 1",
        publisher.PublishSnapshotAsync(counters, apps, jobs).GetAwaiter().GetResult() && publisher.HighestSeq == 1);
    Check("delta push advances to seq 2",
        publisher.PublishDeltaAsync(1, counters, apps, jobs).GetAwaiter().GetResult() && publisher.HighestSeq == 2);
    Check("heartbeat push advances to seq 3",
        publisher.PublishHeartbeatAsync(7, counters).GetAwaiter().GetResult() && publisher.HighestSeq == 3);
    Check("publisher pushed three envelopes", pushed.Count == 3);

    // Every pushed envelope opens through the SHIPPING receiver under k_e2p as the intended kind.
    var recv = new EnvelopeReceiver(activeKeyId);
    string KindOf(string envJson)
    {
        var e = JsonNode.Parse(envJson)!.AsObject();
        var env = new ReceivedEnvelope((int)e["v"]!, (string)e["pairing"]!, (string)e["dir"]!, (long)e["seq"]!,
            (string)e["ts"]!, (string)e["key_id"]!, (string)e["nonce"]!, (string)e["ciphertext"]!,
            e["sig"] is null ? null : (string)e["sig"]!);
        var r = recv.Receive(env, _ => kE2p);
        return r.Accepted ? r.Kind! : $"REJECTED:{r.Error?.ToWire()}";
    }
    Check("pushed snapshot is accepted as kind=snapshot", KindOf(pushed[0]) == "snapshot");
    Check("pushed delta is accepted as kind=delta", KindOf(pushed[1]) == "delta");
    Check("pushed heartbeat is accepted as kind=heartbeat", KindOf(pushed[2]) == "heartbeat");

    var first = JsonNode.Parse(pushed[0])!.AsObject();
    Check("pushed envelope is e2p, names the active key, and carries no sig",
        (string)first["dir"]! == "e2p" && (string)first["key_id"]! == activeKeyId && first["sig"] is null);
    Check("pushed envelopes use distinct nonces",
        pushed.Select(p => (string)JsonNode.Parse(p)!["nonce"]!).Distinct().Count() == pushed.Count);

    // A failed push reports failure and BURNS the seq — it is never reused — so the next push jumps to 5.
    sinkOk = false;
    Check("a failed push reports failure but still burns the seq",
        !publisher.PublishHeartbeatAsync(8, counters).GetAwaiter().GetResult() && publisher.HighestSeq == 4);
    sinkOk = true;
    Check("the next push resumes at seq 5, leaving a gap at 4",
        publisher.PublishHeartbeatAsync(9, counters).GetAwaiter().GetResult() && publisher.HighestSeq == 5);
    Check("receiver accepts the post-gap envelope (gaps are legitimate)", KindOf(pushed[3]) == "heartbeat");

    var evEvents = new[] { new EvidenceEvent(1, "2026-07-23T09:00:11Z", "engine", "scout_ingest", "scout", "b41f") };
    Check("publisher publishes evidence as kind=evidence",
        publisher.PublishEvidenceAsync(true, null, 2, evEvents).GetAwaiter().GetResult() && KindOf(pushed[4]) == "evidence");

    // F4: a publisher resumed from a persisted seq continues ABOVE it. The phone's high-water mark
    // survives a restart, so an engine that resumed at seq 1 would have everything -- including the
    // recovery snapshot -- rejected as replay. startSeq=N means the first push is seq N+1.
    var resumed = new SyncPublisher(kE2p, pairingId, activeKeyId, (_, _) => Task.FromResult(true),
        startSeq: 41, clock: () => new DateTimeOffset(2026, 7, 23, 12, 0, 0, TimeSpan.Zero), nonceSource: nonces);
    Check("publisher resumes above a persisted seq (F4)",
        resumed.HighestSeq == 41
        && resumed.PublishHeartbeatAsync(1, counters).GetAwaiter().GetResult()
        && resumed.HighestSeq == 42);

    var badKey = false;
    try { _ = new SyncPublisher(new byte[16], pairingId, activeKeyId, sink); }
    catch (ArgumentException) { badKey = true; }
    Check("publisher rejects a wrong-length k_e2p", badKey);
}

// ---------------------------------------------------------------- entitlement wire conformance (P4)
//
// `entitlement` is a state-changing p2e kind. This proves the WIRE layer (P4 §2.2): each
// vector decrypts under k_p2e to kind=entitlement carrying {original_json, signature}, and the
// envelope's device ECDSA sig verifies under the pairing device key. The RSA verification and
// the distinct accept/reject reasons are the GoogleSignedPayloadVerifier's job (P4 §2.3), which
// consumes the same five vectors.

Console.WriteLine("\n[ entitlement vectors: wire conformance (decrypt + device signature) ]");

var entitlementVectors = vectors.Where(v => (string)v["type"]! == "entitlement").ToList();
Check("entitlement suite has a valid vector and rejection vectors",
    entitlementVectors.Any(v => (bool)v["valid"]!) && entitlementVectors.Any(v => !(bool)v["valid"]!));

foreach (var v in entitlementVectors.OrderBy(v => (string)v["name"]!, StringComparer.Ordinal))
{
    var name = (string)v["name"]!;
    try
    {
        var text = Encoding.UTF8.GetString(EnvelopeCodec.Open(
            Convert.FromHexString((string)v["key_hex"]!), B64u((string)v["nonce_b64u"]!),
            (string)v["aad"]!, B64u((string)v["ciphertext_b64u"]!)));
        var plain = JsonNode.Parse(text)!.AsObject();
        Check($"{name} decrypts to kind=entitlement with {{original_json, signature}}",
            (string?)plain["kind"] == "entitlement"
            && plain["body"]!["original_json"] is not null && plain["body"]!["signature"] is not null
            && Canonical(plain) == Canonical(v["plaintext_json"]));
    }
    catch (Exception ex) { Check($"{name} decrypts to kind=entitlement", false, ex.GetType().Name); }

    // A state-changing p2e kind MUST carry a valid device sig, over the same pairing device key.
    var ciphertext = B64u((string)v["ciphertext_b64u"]!);
    var input = DeviceSignature.SigInput((string)v["aad"]!, (string)v["nonce_b64u"]!, ciphertext);
    Check($"{name} carries the device ECDSA sig and it verifies under the pairing key",
        v["envelope_json"]!["sig"] is not null
        && DeviceSignature.Verify(devicePub, input, B64u((string)v["envelope_json"]!["sig"]!)));
}

// The signature field is Play's STANDARD base64 (not the envelope's base64url). Decoding it as
// base64url MUST fail -- which is exactly why §4.3.2 flags it as payload content, not framing.
{
    var validEnt = entitlementVectors.Single(v => (string)v["name"]! == "entitlement-valid");
    var sigField = (string)validEnt["plaintext_json"]!["body"]!["signature"]!;
    Check("entitlement signature decodes as standard base64 to a 2048-bit RSA signature (256 bytes)",
        Convert.TryFromBase64String(sigField, new byte[512], out var written) && written == 256);
    Check("entitlement signature is rejected by the envelope base64url decoder (it is payload content)",
        !Base64Url.TryDecode(sigField, out _));
}

// ---------------------------------------------------------------- entitlement verifier + service (P4)
//
// The GoogleSignedPayloadVerifier (option C) against all five vectors: each maps to its distinct
// rejection reason, so a check firing early would surface as a wrong reason. Then EntitlementService's
// apply/refresh/grace lifecycle, driven by an injected clock and an in-memory flag store (no phone, no
// account, no store dependency needed).

Console.WriteLine("\n[ entitlement verifier + service (P4 §2.3) ]");

EntitlementReject ExpectedReject(string expect) => expect switch
{
    "accepted" => EntitlementReject.None,
    "signature_invalid" => EntitlementReject.SignatureInvalid,
    "wrong_product" => EntitlementReject.WrongProduct,
    "wrong_package" => EntitlementReject.WrongPackage,
    "not_purchased" => EntitlementReject.NotPurchased,
    _ => throw new InvalidOperationException($"unknown expect '{expect}'"),
};

GoogleSignedPayloadVerifier VerifierFor(JsonObject ent) => new(
    (string)ent["rsa_pub_spki_b64"]!,
    (string)ent["package_name_expected"]!,
    ent["product_ids_expected"]!.AsArray().Select(x => (string)x!).ToHashSet(StringComparer.Ordinal),
    (int)ent["purchase_state_purchased"]!);

foreach (var v in entitlementVectors.OrderBy(v => (string)v["name"]!, StringComparer.Ordinal))
{
    var name = (string)v["name"]!;
    var ent = v["entitlement"]!.AsObject();
    var body = v["plaintext_json"]!["body"]!.AsObject();
    var verdict = VerifierFor(ent).Verify((string)body["original_json"]!, (string)body["signature"]!);
    var expect = (string)ent["expect"]!;
    Check($"verifier: {name} -> {expect}",
        verdict.Accepted == (expect == "accepted") && verdict.Reason == ExpectedReject(expect),
        $"got accepted={verdict.Accepted} reason={verdict.Reason}");
}

{
    // The accepted verdict surfaces exactly the fields the engine audits.
    var v = entitlementVectors.Single(v => (string)v["name"]! == "entitlement-valid");
    var body = v["plaintext_json"]!["body"]!.AsObject();
    var verdict = VerifierFor(v["entitlement"]!.AsObject()).Verify((string)body["original_json"]!, (string)body["signature"]!);
    Check("verifier: accepted verdict carries product/order/acknowledged",
        verdict.ProductId == "pro_unlock" && verdict.OrderId == "GPA.3390-8461-2039-11123" && verdict.Acknowledged);

    bool badKeyThrew = false;
    try { _ = new GoogleSignedPayloadVerifier("not valid base64 %%%", "app.careerseeker.dashboard", new HashSet<string> { "pro_unlock" }); }
    catch (ArgumentException) { badKeyThrew = true; }
    Check("verifier: a malformed public key fails fast at construction", badKeyThrew);
}

{
    // Service lifecycle: apply / refresh / grace / rejection-is-inert, with an injected clock.
    var v = entitlementVectors.Single(x => (string)x["name"]! == "entitlement-valid");
    var body = v["plaintext_json"]!["body"]!.AsObject();
    var oj = (string)body["original_json"]!;
    var sig = (string)body["signature"]!;
    var wrongBody = entitlementVectors.Single(x => (string)x["name"]! == "entitlement-wrong-product")["plaintext_json"]!["body"]!.AsObject();

    var store = new FakeEntitlementStore();
    var now = new DateTimeOffset(2026, 7, 24, 0, 0, 0, TimeSpan.Zero);
    var svc = new EntitlementService(VerifierFor(v["entitlement"]!.AsObject()), store, () => now);

    Check("service: not entitled before any apply", !svc.IsEntitled());

    var applied = svc.Apply(oj, sig, "abcd1234deadbeef");
    Check("service: a valid apply is accepted and enables Pro", applied.Accepted && svc.IsEntitled());
    Check("service: apply audits product/order/device fingerprint",
        store.Audits.Count == 1 && store.Audits[0] == ("pro_unlock", "GPA.3390-8461-2039-11123", "abcd1234deadbeef", true));

    now = now.AddDays(29);
    Check("service: entitled within the 30-day grace window", svc.IsEntitled());
    now = now.AddDays(2); // 31 days since the last successful verify
    Check("service: entitlement lapses once grace expires (revocation by absence)", !svc.IsEntitled());

    var reapplied = svc.Apply(oj, sig, "abcd1234deadbeef");
    Check("service: a re-report refreshes the grace clock and re-activates Pro", reapplied.Accepted && svc.IsEntitled());

    var auditsBefore = store.Audits.Count;
    var stateBefore = store.Load();
    var rejected = svc.Apply((string)wrongBody["original_json"]!, (string)wrongBody["signature"]!, "abcd1234deadbeef");
    Check("service: a rejected apply changes no state and writes no audit event",
        !rejected.Accepted && rejected.Reason == EntitlementReject.WrongProduct
        && store.Audits.Count == auditsBefore && Equals(store.Load(), stateBefore));
}

// ---------------------------------------------------------------- entitlement_ack (S5, §4.3.3)
//
// The engine's answer to a verified receipt, and the ONLY payload that may unlock Pro on the phone.
// Until this section the two ack vectors had no consumer on either side (§10.2 said so in as many
// words), so they pinned a body that nothing produced: `entitlement_ack` appeared in the engine
// exactly once, as a string in Protocol.ShippingKinds.
//
// The assertion is byte equality against the vector, not field-by-field agreement. The vectors were
// generated by Node; if the C# builder emits the same BYTES under the AEAD then an engine-built ack
// is indistinguishable on the wire from the published artifact the phone's applier was written
// against -- which is the property a shared vector exists to give, and one that a field-by-field
// check would pass while the two implementations disagreed about field order or an omitted null.

Console.WriteLine("\n[ entitlement_ack: the engine builds §4.3.3's body byte-identically (S5) ]");

var ackVectors = vectors.Where(v => (string)v["type"]! == "entitlement_ack").ToList();
Check("suite carries the entitlement_ack vectors, both valid",
    ackVectors.Count == 2 && ackVectors.All(v => (bool)v["valid"]!));

foreach (var v in ackVectors.OrderBy(v => (string)v["name"]!, StringComparer.Ordinal))
{
    var name = (string)v["name"]!;
    var key = Convert.FromHexString((string)v["key_hex"]!);
    var nonce = B64u((string)v["nonce_b64u"]!);
    var aad = (string)v["aad"]!;
    var body = v["plaintext_json"]!["body"]!.AsObject();

    var built = SyncPayloads.EntitlementAck(
        (string)body["product_id"]!, (string)body["acknowledged_at"]!, (string?)body["order_id"]);

    var vectorPlaintext = EnvelopeCodec.Open(key, nonce, aad, B64u((string)v["ciphertext_b64u"]!));
    Check($"{name}: SyncPayloads.EntitlementAck reproduces the vector plaintext byte for byte",
        built.SequenceEqual(vectorPlaintext),
        $"built={Encoding.UTF8.GetString(built)} vector={Encoding.UTF8.GetString(vectorPlaintext)}");

    // AES-GCM is deterministic given key+nonce+aad+plaintext, so this follows from the line above --
    // asserted anyway because it is the claim that actually matters: an ack this engine seals is the
    // same ciphertext the phone's applier was written against.
    Check($"{name}: re-sealing the built body reproduces the vector ciphertext exactly",
        Base64Url.Encode(EnvelopeCodec.Seal(key, nonce, aad, built)) == (string)v["ciphertext_b64u"]!);

    Check($"{name}: is e2p and carries no sig (the engine holds no device signing key, §4.3.3)",
        (string?)v["envelope_json"]!["dir"] == "e2p" && v["envelope_json"]!["sig"] is null);
}

{
    // order_id's optionality is the reason the pair exists. A builder that wrote `"order_id": null`
    // instead of omitting the key would still round-trip through a lenient reader and would still
    // fail here -- which is the point: the absent form is a wire fact, not a serializer preference.
    var withOrder = ackVectors.Single(v => (string)v["name"]! == "entitlement-ack");
    var without = ackVectors.Single(v => (string)v["name"]! == "entitlement-ack-no-order-id");

    var omitted = Encoding.UTF8.GetString(SyncPayloads.EntitlementAck("pro_unlock", "2026-06-11T14:02:11Z"));
    Check("entitlement_ack omits order_id entirely when absent (never a literal null)",
        !omitted.Contains("order_id") && !omitted.Contains("null"));
    Check("entitlement_ack carries order_id verbatim when present",
        Encoding.UTF8.GetString(SyncPayloads.EntitlementAck("pro_unlock", "2026-06-11T14:02:11Z", "GPA.3390-8461-2039-11123"))
            .Contains("\"order_id\":\"GPA.3390-8461-2039-11123\""));
    Check("the two ack vectors differ only by order_id (same product, same grant)",
        (string?)withOrder["plaintext_json"]!["body"]!["product_id"]
            == (string?)without["plaintext_json"]!["body"]!["product_id"]
        && (string?)withOrder["plaintext_json"]!["body"]!["acknowledged_at"]
            == (string?)without["plaintext_json"]!["body"]!["acknowledged_at"]
        && without["plaintext_json"]!["body"]!["order_id"] is null);

    Check("entitlement_ack is a shipping kind and is not state-changing (it is e2p)",
        Protocol.ShippingKinds.Contains("entitlement_ack") && !Protocol.StateChangingKinds.Contains("entitlement_ack"));
}

// ---------------------------------------------------------------- inbound dispatcher (P4 §2.4)
//
// The inbound path routes each accepted p2e kind. entitlement/doc_edit cases reuse the signed vectors;
// outcome/pull_request are minted fresh here with the pairing device private key (pairing-basic carries
// device_sig.d_hex), so the dispatcher sees genuinely-signed envelopes. Each case uses a fresh dispatcher
// (its own receiver) so the per-direction seq tracker never crosses cases.

Console.WriteLine("\n[ inbound dispatcher routes each p2e kind (P4 §2.4) ]");

{
    var pairingId = (string)index["pairing_id"]!;
    var kP2e = Convert.FromHexString("0f1e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0");
    var deviceD = Convert.FromHexString((string)pairingBasic["device_sig"]!["d_hex"]!);
    using var deviceSigner = ECDsa.Create(new ECParameters
    {
        Curve = ECCurve.NamedCurves.nistP256, D = deviceD,
        Q = new ECPoint { X = devicePub[1..33], Y = devicePub[33..] },
    });
    var fingerprint = DeviceSignature.Fingerprint(devicePub);
    var entConfig = entitlementVectors.Single(v => (string)v["name"]! == "entitlement-valid")["entitlement"]!.AsObject();
    var nonceSeed = 100;

    ReceivedEnvelope SealP2e(long seq, object plaintext, bool sign)
    {
        var header = new EnvelopeHeader(1, pairingId, "p2e", seq, "2026-07-24T00:00:00Z", activeKeyId);
        var aad = header.Aad();
        var nonce = new byte[Protocol.NonceBytes]; nonce[0] = (byte)nonceSeed++; nonce[1] = 0x2e;
        var ct = EnvelopeCodec.Seal(kP2e, nonce, aad, JsonSerializer.SerializeToUtf8Bytes(plaintext));
        string? sig = null;
        if (sign)
        {
            var input = DeviceSignature.SigInput(aad, Base64Url.Encode(nonce), ct);
            sig = Base64Url.Encode(deviceSigner.SignData(Encoding.ASCII.GetBytes(input), HashAlgorithmName.SHA256));
        }
        return new ReceivedEnvelope(1, pairingId, "p2e", seq, "2026-07-24T00:00:00Z", activeKeyId,
            Base64Url.Encode(nonce), Base64Url.Encode(ct), sig);
    }

    InboundDispatcher MakeDispatcher(RecordingOutcomeApplier? outcome, RecordingRepublisher? republisher,
        RecordingAckPublisher? acks = null)
    {
        var receiver = new EnvelopeReceiver(activeKeyId, devicePub);
        var svc = new EntitlementService(VerifierFor(entConfig), new FakeEntitlementStore(),
            () => new DateTimeOffset(2026, 7, 24, 0, 0, 0, TimeSpan.Zero));
        return new InboundDispatcher(receiver, svc, fingerprint, _ => kP2e, outcome, republisher, acks);
    }

    // entitlement (valid) -> applied, AND the phone is told. The ack is the only thing that unlocks
    // Pro there (§4.3.3), so "applied" without a published ack is a user who paid and saw nothing.
    var appliedAcks = new RecordingAckPublisher();
    var rApplied = MakeDispatcher(null, null, appliedAcks)
        .DispatchAsync(ToReceived(entitlementVectors.Single(v => (string)v["name"]! == "entitlement-valid")["envelope_json"]!.AsObject()))
        .GetAwaiter().GetResult();
    Check("dispatch: entitlement-valid -> EntitlementApplied", rApplied.Outcome == InboundOutcome.EntitlementApplied);
    Check("dispatch: an applied entitlement publishes exactly one entitlement_ack",
        appliedAcks.Published.Count == 1);

    // Read the expected product/order out of the Play-signed receipt the verifier just checked, so this
    // asserts the ack echoes THAT record -- not a constant, and not anything the phone chose to send.
    var validReceipt = JsonNode.Parse((string)entitlementVectors
        .Single(v => (string)v["name"]! == "entitlement-valid")["plaintext_json"]!["body"]!["original_json"]!)!.AsObject();
    Check("dispatch: the ack names the product and order from the VERIFIED receipt, not the request body",
        appliedAcks.Published.Count == 1
        && appliedAcks.Published[0].ProductId == (string?)validReceipt["productId"]
        && appliedAcks.Published[0].OrderId == (string?)validReceipt["orderId"]);

    // entitlement (wrong product) -> rejected with the distinct reason, and NO ack. §4.3.3 has no
    // negative form: an ack means granted, full stop. This is the assertion that a future refactor
    // returning "ack with a flag" has to fail, on the one path that turns a paid feature on.
    var rejectedAcks = new RecordingAckPublisher();
    var rRejected = MakeDispatcher(null, null, rejectedAcks)
        .DispatchAsync(ToReceived(entitlementVectors.Single(v => (string)v["name"]! == "entitlement-wrong-product")["envelope_json"]!.AsObject()))
        .GetAwaiter().GetResult();
    Check("dispatch: entitlement-wrong-product -> EntitlementRejected(WrongProduct)",
        rRejected.Outcome == InboundOutcome.EntitlementRejected && rRejected.EntitlementReason == EntitlementReject.WrongProduct);
    Check("dispatch: a REJECTED entitlement publishes no ack at all (§4.3.3 has no negative form)",
        rejectedAcks.Published.Count == 0);

    // The seam stays optional, like the other two: a dispatcher with no ack publisher still applies.
    var rNoSeam = MakeDispatcher(null, null)
        .DispatchAsync(ToReceived(entitlementVectors.Single(v => (string)v["name"]! == "entitlement-valid")["envelope_json"]!.AsObject()))
        .GetAwaiter().GetResult();
    Check("dispatch: a null ack publisher leaves the seam inert without failing the apply",
        rNoSeam.Outcome == InboundOutcome.EntitlementApplied);

    // outcome (signed, minted fresh) -> handed to the applier
    var outcomeApplier = new RecordingOutcomeApplier();
    var rOutcome = MakeDispatcher(outcomeApplier, null).DispatchAsync(
        SealP2e(1, new { kind = "outcome", body = new { app_id = "app_1", outcome = "interview", at = "2026-07-24T00:00:00Z" } }, sign: true))
        .GetAwaiter().GetResult();
    Check("dispatch: signed outcome -> OutcomeApplied and handed to the §2.5 applier",
        rOutcome.Outcome == InboundOutcome.OutcomeApplied && outcomeApplier.Applied.Count == 1
        && outcomeApplier.Applied[0].Body.Contains("interview") && outcomeApplier.Applied[0].Fingerprint == fingerprint);

    // pull_request (not state-changing, so unsigned) -> re-publish snapshot from since_seq
    var republisher = new RecordingRepublisher();
    var rPull = MakeDispatcher(null, republisher).DispatchAsync(
        SealP2e(1, new { kind = "pull_request", body = new { since_seq = 7L } }, sign: false))
        .GetAwaiter().GetResult();
    Check("dispatch: pull_request -> SnapshotRepublished(since_seq=7)",
        rPull.Outcome == InboundOutcome.SnapshotRepublished && republisher.LastSince == 7L);

    // doc_edit (signed) -> recognised but unimplemented; the apply path is NEVER touched
    var rDoc = MakeDispatcher(null, null)
        .DispatchAsync(ToReceived(envelopeVectors.Single(v => (string)v["name"]! == "doc-edit-signed")["envelope_json"]!.AsObject()))
        .GetAwaiter().GetResult();
    Check("dispatch: doc_edit -> DocEditUnimplemented (P3's surface, not applied)", rDoc.Outcome == InboundOutcome.DocEditUnimplemented);
    Check("dispatch: doc_edit reply code is 'unimplemented' and distinct from unknown_kind",
        InboundDispatcher.DocEditReplyCode == "unimplemented" && SyncError.Unimplemented.ToWire() == "unimplemented"
        && SyncError.Unimplemented.ToWire() != SyncError.UnknownKind.ToWire());

    // a receiver rejection (unsigned state-changing kind) passes through as ReceiveRejected, unapplied
    var rBad = MakeDispatcher(null, null)
        .DispatchAsync(ToReceived(envelopeVectors.Single(v => (string)v["name"]! == "sig-missing-on-doc-edit")["envelope_json"]!.AsObject()))
        .GetAwaiter().GetResult();
    Check("dispatch: an unsigned state-changing kind is ReceiveRejected(bad_signature), never dispatched",
        rBad.Outcome == InboundOutcome.ReceiveRejected && rBad.ReceiveError == SyncError.BadSignature);
}

// ---------------------------------------------------------------- inbound pump (S5 host wiring)
//
// The transport loop that turns the dispatcher above from a library into something the running engine
// does. Everything here is an ordering rule, and ordering rules are exactly what a live smoke against a
// relay cannot pin: the smoke proves the happy path round-trips, while what actually needs proving is
// what the cursor does when the relay is hostile or merely broken.
//
// The relay is faked, and that is the point — this asserts against pages a real relay would never
// serve. §2 says the relay is blind but NOT trusted; every page below is one it is free to construct.

Console.WriteLine("\n[ inbound pump: the engine's p2e transport loop (S5, §6.1/§6.2/§6.4) ]");

{
    var pairingId = (string)index["pairing_id"]!;
    var kP2e = Convert.FromHexString("0f1e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0");
    var kE2p = Convert.FromHexString("1122334455667788990011223344556677889900112233445566778899001122");
    var deviceD = Convert.FromHexString((string)pairingBasic["device_sig"]!["d_hex"]!);
    using var deviceSigner = ECDsa.Create(new ECParameters
    {
        Curve = ECCurve.NamedCurves.nistP256, D = deviceD,
        Q = new ECPoint { X = devicePub[1..33], Y = devicePub[33..] },
    });
    var fingerprint = DeviceSignature.Fingerprint(devicePub);
    var entConfig = entitlementVectors.Single(v => (string)v["name"]! == "entitlement-valid")["entitlement"]!.AsObject();
    var pumpNonce = 200;

    // One sealed envelope, as the relay would serve it: a bare §3 object (§2.1), not a wrapper.
    JsonElement Wire(string dir, long seq, byte[] key, object plaintext, bool sign, string? extraField = null)
    {
        var header = new EnvelopeHeader(1, pairingId, dir, seq, "2026-07-24T00:00:00Z", activeKeyId);
        var aad = header.Aad();
        var nonce = new byte[Protocol.NonceBytes]; nonce[0] = (byte)pumpNonce++; nonce[1] = 0x5c;
        var ct = EnvelopeCodec.Seal(key, nonce, aad, JsonSerializer.SerializeToUtf8Bytes(plaintext));
        var o = new JsonObject
        {
            ["v"] = 1, ["pairing"] = pairingId, ["dir"] = dir, ["seq"] = seq,
            ["ts"] = "2026-07-24T00:00:00Z", ["key_id"] = activeKeyId,
            ["nonce"] = Base64Url.Encode(nonce), ["ciphertext"] = Base64Url.Encode(ct),
        };
        if (sign)
        {
            var input = DeviceSignature.SigInput(aad, Base64Url.Encode(nonce), ct);
            o["sig"] = Base64Url.Encode(deviceSigner.SignData(Encoding.ASCII.GetBytes(input), HashAlgorithmName.SHA256));
        }
        if (extraField is not null) o[extraField] = "x";
        return JsonDocument.Parse(o.ToJsonString()).RootElement.Clone();
    }

    // A well-formed §3 envelope whose ciphertext is not openable under any key the engine holds. This is
    // the shape the cursor rules exist for: it PARSES, so it has a header seq, and that seq is
    // authenticated by nothing at all.
    JsonElement Undecryptable(long seq) => Wire(Protocol.PhoneToEngine, seq, kE2p, new { kind = "outcome", body = new { } }, sign: true);

    (InboundPump Pump, RecordingAckPublisher Acks, List<long> Persisted) MakePump(
        IReadOnlyList<IReadOnlyList<JsonElement>> pages, long latest, long resumeFrom = 0)
    {
        var acks = new RecordingAckPublisher();
        var persisted = new List<long>();
        var receiver = new EnvelopeReceiver(activeKeyId, devicePub,
            resume: resumeFrom > 0 ? new Dictionary<string, long>(StringComparer.Ordinal) { [Protocol.PhoneToEngine] = resumeFrom } : null);
        var dispatcher = new InboundDispatcher(
            receiver,
            new EntitlementService(VerifierFor(entConfig), new FakeEntitlementStore(),
                () => new DateTimeOffset(2026, 7, 24, 0, 0, 0, TimeSpan.Zero)),
            fingerprint,
            dir => dir == Protocol.PhoneToEngine ? kP2e : kE2p,
            new RecordingOutcomeApplier(), new RecordingRepublisher(), acks);
        var served = 0;
        var pump = new InboundPump(
            (_, _) => Task.FromResult<InboundPage?>(
                served < pages.Count ? new InboundPage(pages[served++], latest) : new InboundPage(Array.Empty<JsonElement>(), latest)),
            dispatcher, Protocol.PhoneToEngine, resumeFrom, persisted.Add);
        return (pump, acks, persisted);
    }

    // --- the happy path: a signed outcome is dispatched and its seq becomes the persisted mark
    {
        var outcome = Wire(Protocol.PhoneToEngine, 4, kP2e,
            new { kind = "outcome", body = new { app_id = "app_1", outcome = "interview", at = "2026-07-24T00:00:00Z" } }, sign: true);
        var (pump, _, persisted) = MakePump(new[] { new[] { outcome } }, latest: 4);
        var report = pump.DrainAsync().GetAwaiter().GetResult();
        Check("pump: an accepted envelope is dispatched, moves the cursor, and persists its seq",
            report.Outcomes.SequenceEqual(new[] { InboundOutcome.OutcomeApplied })
            && report.Cursor == 4 && persisted.SequenceEqual(new[] { 4L }) && !report.MoreAvailable);
    }

    // --- the headline: a parseable, unauthenticated seq CANNOT walk the cursor past `latest`.
    // Without the bound this page truncates history: the cursor jumps to 1,000,000, never moves
    // backwards, and every real envelope below it is never requested again -- performed by a party that
    // decrypted nothing. §6.4 permits the advance and bounds it; the bound is what this asserts.
    {
        var (pump, _, persisted) = MakePump(new[] { new[] { Undecryptable(1_000_000) } }, latest: 5);
        var report = pump.DrainAsync().GetAwaiter().GetResult();
        Check("pump: a crafted seq of 1,000,000 on an undecryptable envelope is capped at the page's latest",
            report.Cursor == 5);
        Check("pump: that envelope is reported as a rejection and never dispatched",
            report.Rejections.SequenceEqual(new[] { SyncError.DecryptFailed }) && report.Outcomes.Count == 0);
        Check("pump: an unauthenticated seq is never persisted as the replay mark",
            persisted.Count == 0);
    }

    // --- the same rule for an element that fails the §3 parse outright (unknown top-level field)
    {
        var (pump, _, persisted) = MakePump(new[] { new[] { Wire(Protocol.PhoneToEngine, 999, kP2e, new { kind = "outcome", body = new { } }, sign: true, extraField: "shadow") } }, latest: 3);
        var report = pump.DrainAsync().GetAwaiter().GetResult();
        Check("pump: an element failing the §3 parse advances the cursor only as far as latest",
            report.Cursor == 3 && report.Rejections.SequenceEqual(new[] { SyncError.DecryptFailed }));
        // Added after a mutation survived: the assertion above pins the cursor and said nothing about
        // the mark, so writing a claimed seq into the persisted replay mark from this branch was caught
        // by nothing. An unparseable element is the LEAST authenticated thing on the page.
        Check("pump: an element failing the §3 parse persists no replay mark either", persisted.Count == 0);
    }

    // --- an ACCEPTED seq is authenticated, so it is the one number that moves the cursor unbounded.
    // This is the other half of the rule: bounding everything would be the stall §6.2 forbids.
    {
        var accepted = Wire(Protocol.PhoneToEngine, 9, kP2e, new { kind = "pull_request", body = new { since_seq = 0 } }, sign: false);
        var (pump, _, persisted) = MakePump(new[] { new[] { accepted } }, latest: 3);
        var report = pump.DrainAsync().GetAwaiter().GetResult();
        Check("pump: an accepted envelope's AUTHENTICATED seq moves the cursor past a lying latest",
            report.Cursor == 9 && persisted.SequenceEqual(new[] { 9L }));
    }

    // --- the cursor never moves backwards, whatever the page claims
    {
        var (pump, _, _) = MakePump(new[] { new[] { Undecryptable(2) } }, latest: 50, resumeFrom: 20);
        var report = pump.DrainAsync().GetAwaiter().GetResult();
        Check("pump: the cursor never moves backwards (seeded at 20, page claims 2)", report.Cursor == 20);
    }

    // --- the engine's own e2p traffic, served back on the p2e page.
    // Every downstream check passes for this envelope -- no sig is required of an e2p envelope, the
    // replay counter consulted is the *e2p* one which resume never seeds, and keyForDir hands over the
    // e2p key so the tag verifies. Without the pump's direction guard it is ACCEPTED, and `onAccepted`
    // writes an e2p seq into the persisted p2e mark. Push that mark past the phone's counter and every
    // genuine phone envelope afterwards is refused as a replay: a silent, permanent, one-way outage.
    {
        var ownTraffic = Wire(Protocol.EngineToPhone, 900, kE2p, new { kind = "snapshot", body = new { } }, sign: false);
        var (pump, _, persisted) = MakePump(new[] { new[] { ownTraffic } }, latest: 6);
        var report = pump.DrainAsync().GetAwaiter().GetResult();
        Check("pump: an e2p envelope replayed onto the p2e page is refused before dispatch",
            report.Outcomes.Count == 0 && report.Rejections.SequenceEqual(new[] { SyncError.DecryptFailed }));
        Check("pump: and it cannot corrupt the p2e replay mark or the cursor",
            persisted.Count == 0 && report.Cursor == 6);
    }

    // --- resumption: the persisted mark is what refuses an already-applied envelope after a restart
    {
        var replayed = Wire(Protocol.PhoneToEngine, 5, kP2e,
            new { kind = "outcome", body = new { app_id = "app_1", outcome = "interview", at = "2026-07-24T00:00:00Z" } }, sign: true);
        var (fresh, _, freshPersisted) = MakePump(new[] { new[] { replayed } }, latest: 5);
        var freshReport = fresh.DrainAsync().GetAwaiter().GetResult();
        var (resumed, _, resumedPersisted) = MakePump(new[] { new[] { replayed } }, latest: 5, resumeFrom: 5);
        var resumedReport = resumed.DrainAsync().GetAwaiter().GetResult();
        Check("pump: an unseeded receiver ACCEPTS the already-applied envelope (this is what the mark prevents)",
            freshReport.Outcomes.SequenceEqual(new[] { InboundOutcome.OutcomeApplied }) && freshPersisted.SequenceEqual(new[] { 5L }));
        Check("pump: a receiver resumed from the persisted mark refuses it as a replay instead",
            resumedReport.Outcomes.Count == 0
            && resumedReport.Rejections.SequenceEqual(new[] { SyncError.ReplayRejected })
            && resumedPersisted.Count == 0);
    }

    // --- a transport failure arrives as data, never as an exception out of the drain
    {
        var dispatcher = new InboundDispatcher(
            new EnvelopeReceiver(activeKeyId, devicePub),
            new EntitlementService(VerifierFor(entConfig), new FakeEntitlementStore(), () => DateTimeOffset.UtcNow),
            fingerprint, _ => kP2e);
        var pump = new InboundPump((_, _) => Task.FromResult<InboundPage?>(null), dispatcher, Protocol.PhoneToEngine, resumeFrom: 7);
        var report = pump.DrainAsync().GetAwaiter().GetResult();
        Check("pump: a relay that did not answer reports PullFailed and leaves the cursor untouched",
            report.PullFailed && report.Cursor == 7 && report.Pulled == 0 && !report.MoreAvailable);
    }

    // --- more-available is the paging signal the bridge's drain loop follows
    {
        var (pump, _, _) = MakePump(new[] { new[] { Undecryptable(2) } }, latest: 40);
        var report = pump.DrainAsync().GetAwaiter().GetResult();
        Check("pump: cursor below the page's latest reports more available", report.MoreAvailable && report.Cursor == 2);
    }
}

Console.WriteLine("\n[ the replay mark raises only (§6.2) ]");

{
    var tracker = new SequenceTracker();
    tracker.Resume(Protocol.PhoneToEngine, 12);
    tracker.Resume(Protocol.PhoneToEngine, 4);
    Check("resume raises the replay mark and refuses to lower it",
        tracker.HighestAccepted(Protocol.PhoneToEngine) == 12 && !tracker.Accept(Protocol.PhoneToEngine, 12));
    Check("resume is per direction: seeding p2e leaves e2p at zero",
        tracker.HighestAccepted(Protocol.EngineToPhone) == 0);
}

// ---------------------------------------------------------------- protocol rules

Console.WriteLine("\n[ protocol rules independent of any single vector ]");

Check("base64url decoder rejects padding", !Base64Url.TryDecode("AAAA==", out _));
Check("base64url decoder rejects standard-alphabet '+'", !Base64Url.TryDecode("AA+A", out _));
Check("base64url decoder rejects standard-alphabet '/'", !Base64Url.TryDecode("AA/A", out _));
Check("base64url decoder accepts unpadded input", Base64Url.TryDecode("AAAA", out var three) && three.Length == 3);
Check("base64url round-trips", Base64Url.TryDecode(Base64Url.Encode(new byte[] { 1, 2, 3, 250 }), out var rt) && rt.SequenceEqual(new byte[] { 1, 2, 3, 250 }));

Check("all valid-vector nonces are distinct",
    validEnv.Select(v => (string)v["nonce_b64u"]!).Distinct().Count() == validEnv.Count);
Check("no reserved L2 kind appears in the v1 shipping set",
    !Protocol.ReservedL2Kinds.Intersect(Protocol.ShippingKinds, StringComparer.Ordinal).Any());
Check("'kill' is reserved, not shipping",
    Protocol.ReservedL2Kinds.Contains("kill") && !Protocol.ShippingKinds.Contains("kill"));
Check("state-changing kinds are a subset of shipping kinds",
    Protocol.StateChangingKinds.All(Protocol.ShippingKinds.Contains));
Check("no v1 payload kind implies a send path",
    !Protocol.ShippingKinds.Any(k => k.Contains("send") || k.Contains("submit") || k.Contains("transmit")));
Check("device key fingerprint is 16 lowercase hex chars",
    DeviceSignature.Fingerprint(devicePub) is { Length: 16 } fp && fp.All(c => "0123456789abcdef".Contains(c)));
Check("suite string names its post-quantum successor",
    Protocol.SuiteHybridReserved.Contains("mlkem") && Protocol.SuiteHybridReserved != Protocol.Suite);

// ---------------------------------------------------------------- relay pull result (§2.2)
//
// RelayClient had no offline coverage at all before this section: `grep -rl RelayClient tests/`
// returned only SyncLiveSmoke, which needs a live or local relay and is excluded from the hermetic
// suite. That is how PullAsync stayed partial -- EnsureSuccessStatusCode, GetProperty and GetInt64
// all throw, and nothing offline ever asked what happened when they did.
//
// These drive the real shipping client over a stub transport. The property under test is the one the
// pump's contract states and the signature now carries: a relay that answers badly produces a VALUE,
// never an exception.

Console.WriteLine("\n[ relay pull result ]");

const string PullPairing = "p_AAAAAAAAAAAAAAAA";

async Task<RelayPullResult> Pull(
    Func<HttpRequestMessage, CancellationToken, HttpResponseMessage> respond,
    CancellationToken ct = default)
{
    using var handler = new StubTransport(respond);
    using var httpClient = new HttpClient(handler);
    return await new RelayClient(httpClient, "https://relay.example", PullPairing)
        .PullAsync("bearer-token", "p2e", 7, ct);
}

static HttpResponseMessage Answer(HttpStatusCode status, string body) =>
    new(status) { Content = new StringContent(body, Encoding.UTF8, "application/json") };

// -- the happy path, and the two things about it that are easy to get wrong ------------------
var okResult = await Pull((_, _) => Answer(HttpStatusCode.OK,
    """{"envelopes":[{"seq":8,"dir":"p2e"},{"seq":9,"dir":"p2e"}],"latest":9}"""));
Check("a well-formed page is Ok", okResult is RelayPullResult.Ok, okResult.GetType().Name);
Check("Ok carries every envelope and the latest seq",
    okResult is RelayPullResult.Ok { Envelopes.Count: 2, Latest: 9 });
// The elements are cloned out of a JsonDocument that PullAsync disposes on the way out. Reading one
// after the call has returned is the assertion that the clone is real -- drop the .Clone() and this
// throws ObjectDisposedException rather than failing quietly.
Check("Ok envelopes outlive the JsonDocument they were parsed from",
    okResult is RelayPullResult.Ok ok2 && ok2.Envelopes[1].GetProperty("seq").GetInt64() == 9);

// -- the request itself: nothing offline had ever asserted the wire form ---------------------
HttpRequestMessage? seen = null;
await Pull((req, _) => { seen = req; return Answer(HttpStatusCode.OK, """{"envelopes":[],"latest":0}"""); });
Check("the pull carries the bearer", seen?.Headers.Authorization?.ToString() == "Bearer bearer-token"
    || seen?.Headers.GetValues("Authorization").FirstOrDefault() == "Bearer bearer-token");
Check("the pull addresses /v1/{pairing}/pull with dir and since",
    seen?.RequestUri?.ToString() == $"https://relay.example/v1/{PullPairing}/pull?dir=p2e&since=7",
    seen?.RequestUri?.ToString());
Check("an empty page is Ok, not a failure",
    await Pull((_, _) => Answer(HttpStatusCode.OK, """{"envelopes":[],"latest":0}"""))
        is RelayPullResult.Ok { Envelopes.Count: 0, Latest: 0 });

// -- 401 vs 404: the distinction PQ-S2-4 is about --------------------------------------------
//
// A purged pairing answers 401 on every route (measured under miniflare; §2.3 pins it), so
// Unauthorised covers both "wrong bearer" and "pairing is gone" and the relay refuses to say which.
// 404 on this route means something else entirely -- the id failed the relay's shape check, or the
// route is absent -- and it must not be laundered into the same case.
Check("401 is Unauthorised",
    await Pull((_, _) => Answer(HttpStatusCode.Unauthorized, """{"error":"unauthorized"}"""))
        is RelayPullResult.Unauthorised);
Check("403 is Unauthorised too",
    await Pull((_, _) => Answer(HttpStatusCode.Forbidden, """{"error":"forbidden"}"""))
        is RelayPullResult.Unauthorised);
Check("404 is Misconfigured, NOT Unauthorised and NOT Unavailable",
    await Pull((_, _) => Answer(HttpStatusCode.NotFound, """{"error":"pairing_unknown"}"""))
        is RelayPullResult.Misconfigured);

// -- everything else the relay or the network can do -----------------------------------------
Check("500 is Unavailable",
    await Pull((_, _) => Answer(HttpStatusCode.InternalServerError, "")) is RelayPullResult.Unavailable);
Check("429 is Unavailable",
    await Pull((_, _) => Answer((HttpStatusCode)429, "")) is RelayPullResult.Unavailable);
Check("a transport failure is Unavailable, not an exception",
    await Pull((_, _) => throw new HttpRequestException("no route to host")) is RelayPullResult.Unavailable);
// HttpClient raises TaskCanceledException for its own timeout as well as for caller cancellation.
// With the caller's token NOT cancelled this is the timeout, and a timeout is a relay condition.
Check("a client timeout is Unavailable",
    await Pull((_, _) => throw new TaskCanceledException("timed out")) is RelayPullResult.Unavailable);

// -- a 200 that is not a pull page. This is the class the old code could not express ----------
Check("a 200 carrying an HTML error page is Unavailable",
    await Pull((_, _) => Answer(HttpStatusCode.OK, "<html><body>502 Bad Gateway</body></html>"))
        is RelayPullResult.Unavailable);
Check("a 200 whose root is not an object is Unavailable",
    await Pull((_, _) => Answer(HttpStatusCode.OK, "[]")) is RelayPullResult.Unavailable);
Check("a 200 with no envelopes array is Unavailable",
    await Pull((_, _) => Answer(HttpStatusCode.OK, """{"latest":3}""")) is RelayPullResult.Unavailable);
Check("a 200 whose envelopes is not an array is Unavailable",
    await Pull((_, _) => Answer(HttpStatusCode.OK, """{"envelopes":{},"latest":3}"""))
        is RelayPullResult.Unavailable);
Check("a 200 with no latest is Unavailable",
    await Pull((_, _) => Answer(HttpStatusCode.OK, """{"envelopes":[]}""")) is RelayPullResult.Unavailable);
Check("a 200 whose latest is a string is Unavailable",
    await Pull((_, _) => Answer(HttpStatusCode.OK, """{"envelopes":[],"latest":"3"}"""))
        is RelayPullResult.Unavailable);
Check("a 200 whose latest is fractional is Unavailable",
    await Pull((_, _) => Answer(HttpStatusCode.OK, """{"envelopes":[],"latest":3.5}"""))
        is RelayPullResult.Unavailable);

// -- the one exception that must still escape -------------------------------------------------
//
// Cancellation is the caller's decision, not the relay's. Turning it into Unavailable would tell a
// shutting-down host "the relay did not answer, try again", which is how a stop request becomes a
// loop that will not stop.
using var cancelled = new CancellationTokenSource();
cancelled.Cancel();
var cancellationEscaped = false;
try { await Pull((_, _) => Answer(HttpStatusCode.OK, """{"envelopes":[],"latest":0}"""), cancelled.Token); }
catch (OperationCanceledException) { cancellationEscaped = true; }
Check("caller cancellation propagates rather than becoming a result", cancellationEscaped);

Console.WriteLine($"\n=== {passed} passed, {failed} failed ===");
return failed == 0 ? 0 : 1;

// ---------------------------------------------------------------- helpers

static byte[] B64u(string s) => Base64Url.TryDecode(s, out var b)
    ? b : throw new FormatException($"vector value is not strict base64url: {s[..Math.Min(16, s.Length)]}…");

static string ToHex(JsonNode n) => Convert.ToHexString(Base64Url.TryDecode((string)n!, out var b) ? b : throw new FormatException());

static ReceivedEnvelope ToReceived(JsonObject env) => new(
    (int)env["v"]!, (string)env["pairing"]!, (string)env["dir"]!, (long)env["seq"]!,
    (string)env["ts"]!, (string)env["key_id"]!, (string)env["nonce"]!, (string)env["ciphertext"]!,
    env["sig"] is null ? null : (string)env["sig"]!);

static ECDiffieHellman ImportEcdh(string dHex, string pubB64u)
{
    var pub = Base64Url.TryDecode(pubB64u, out var p) ? p : throw new FormatException();
    return ECDiffieHellman.Create(new ECParameters
    {
        Curve = ECCurve.NamedCurves.nistP256,
        D = Convert.FromHexString(dHex),
        Q = new ECPoint { X = pub[1..33], Y = pub[33..] },
    });
}

static string Canonical(JsonNode? node) => node switch
{
    null => "null",
    JsonObject o => "{" + string.Join(",", o.OrderBy(kv => kv.Key, StringComparer.Ordinal)
        .Select(kv => JsonSerializer.Serialize(kv.Key) + ":" + Canonical(kv.Value))) + "}",
    JsonArray a => "[" + string.Join(",", a.Select(Canonical)) + "]",
    _ => node.ToJsonString(),
};

static string? LocateVectorDirectory()
{
    var candidates = new List<string>();
    var probe = new DirectoryInfo(Directory.GetCurrentDirectory());
    while (probe is not null) { candidates.Add(probe.FullName); probe = probe.Parent; }
    probe = new DirectoryInfo(AppContext.BaseDirectory);
    while (probe is not null) { candidates.Add(probe.FullName); probe = probe.Parent; }
    return candidates
        .Select(root => Path.Combine(root, "docs", "sync-vectors", "v1"))
        .FirstOrDefault(path => Directory.Exists(path) && File.Exists(Path.Combine(path, "index.json")));
}

/// <summary>In-memory <see cref="IEntitlementStateStore"/> for the service lifecycle tests: one flag,
/// a recorded audit list. Stands in for the engine's config table + hash-chained log (wired in §2.4).</summary>
sealed class FakeEntitlementStore : SeekerSvc.Sync.IEntitlementStateStore
{
    private SeekerSvc.Sync.EntitlementState? _state;
    public readonly List<(string ProductId, string OrderId, string Fingerprint, bool Acknowledged)> Audits = new();
    public SeekerSvc.Sync.EntitlementState? Load() => _state;
    public void Save(SeekerSvc.Sync.EntitlementState state) => _state = state;
    public void AuditApplied(string productId, string orderId, string deviceFingerprint, bool acknowledged)
        => Audits.Add((productId, orderId, deviceFingerprint, acknowledged));
}

/// <summary>Recording <see cref="SeekerSvc.Sync.IOutcomeApplier"/> — the §2.5 seam stubbed for the §2.4 routing tests.</summary>
sealed class RecordingOutcomeApplier : SeekerSvc.Sync.IOutcomeApplier
{
    public readonly List<(string Body, string Fingerprint)> Applied = new();
    public Task ApplyAsync(string outcomeBodyJson, string deviceFingerprint, CancellationToken ct = default)
    { Applied.Add((outcomeBodyJson, deviceFingerprint)); return Task.CompletedTask; }
}

/// <summary>Recording <see cref="SeekerSvc.Sync.IEntitlementAckPublisher"/> — captures every §4.3.3 ack the
/// dispatcher emits, so the tests can assert both that an accepted receipt produces one and that a rejected
/// receipt produces none.</summary>
sealed class RecordingAckPublisher : SeekerSvc.Sync.IEntitlementAckPublisher
{
    public readonly List<(string ProductId, string? OrderId)> Published = new();
    public Task PublishEntitlementAckAsync(string productId, string? orderId, CancellationToken ct = default)
    { Published.Add((productId, orderId)); return Task.CompletedTask; }
}

/// <summary>Recording <see cref="SeekerSvc.Sync.ISnapshotRepublisher"/> — captures the since_seq a pull_request asked to resume from.</summary>
sealed class RecordingRepublisher : SeekerSvc.Sync.ISnapshotRepublisher
{
    public long? LastSince;
    public Task RepublishSnapshotAsync(long sinceSeq, CancellationToken ct = default)
    { LastSince = sinceSeq; return Task.CompletedTask; }
}

/// <summary>
/// A stub <see cref="HttpMessageHandler"/> for the pull-result tests: it answers whatever the test
/// hands it, including by throwing, so the real shipping <see cref="SeekerSvc.Sync.RelayClient"/> is
/// the code under test and only the socket is fake.
/// </summary>
sealed class StubTransport(Func<HttpRequestMessage, CancellationToken, HttpResponseMessage> respond) : HttpMessageHandler
{
    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken ct)
    {
        // Mirrors HttpClient: an already-cancelled token fails the send rather than being ignored.
        ct.ThrowIfCancellationRequested();
        return Task.FromResult(respond(request, ct));
    }
}
