// Sync Protocol v1 conformance harness.
//
// Reads the shared test vectors in docs/sync-vectors/v1/ -- the SAME files the Kotlin
// :core tests in ShivaClaw/careerseeker-android consume -- and checks this side of the
// protocol against them. The vectors are generated by Node (docs/sync-vectors/generate.mjs);
// verifying them here is a genuine cross-implementation check rather than a language
// agreeing with itself.
//
// P0 scope: the envelope codec and the rejection rules in docs/Sync-Protocol.md.
// There is no src/Sync yet -- when the real SyncPublisher lands in P1, this harness
// points at it instead of the local helpers below, and the vectors do not change.

using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

int passed = 0, failed = 0;
void Check(string name, bool condition, string? detail = null)
{
    if (condition)
    {
        passed++;
        Console.WriteLine($"  PASS  {name}");
    }
    else
    {
        failed++;
        Console.WriteLine($"  FAIL  {name}{(detail is null ? "" : $"  -- {detail}")}");
    }
}

Console.WriteLine("=== CareerSeeker sync protocol v1 harness ===\n");

const int MaxEnvelopeBytes = 1024 * 1024;
const int NonceBytes = 12;
const int TagBytes = 16;

// The v1 payload kinds, per docs/Sync-Protocol.md section 4.3. Reserved L2 kinds are
// listed separately and must stay rejected, so promoting one is a deliberate, visible
// edit here rather than a silent widening of what the phone can ask the engine to do.
string[] reserved = ["state_change", "gate_request", "gate_resolve", "kill", "config_change", "lesson_proposal", "metric"];
string[] shipping = ["snapshot", "delta", "doc", "evidence", "heartbeat", "conflict", "entitlement_ack", "error",
                     "doc_edit", "outcome", "entitlement", "pull_request"];

var vectorDir = LocateVectorDirectory();
if (vectorDir is null)
{
    Console.WriteLine("  FAIL  vector directory docs/sync-vectors/v1 not found");
    Console.WriteLine("\n=== 0 passed, 1 failed ===");
    return 1;
}

Console.WriteLine($"Vectors: {vectorDir}\n");

// ---------------------------------------------------------------- index

Console.WriteLine("[ vector suite integrity ]");

var index = JsonNode.Parse(File.ReadAllText(Path.Combine(vectorDir, "index.json")))!.AsObject();
var declared = index["vectors"]!.AsArray();
var activeKeyId = (string?)index["active_key_id"];
var onDisk = Directory.GetFiles(vectorDir, "*.json")
    .Select(Path.GetFileNameWithoutExtension)
    .Where(n => n != "index")
    .OrderBy(n => n, StringComparer.Ordinal)
    .ToList();

Check("index declares AES-256-GCM", (string?)index["cipher"] == "AES-256-GCM",
    $"cipher = {(string?)index["cipher"]}");
Check("index envelope limit matches the spec", (int?)index["max_envelope_bytes"] == MaxEnvelopeBytes);
Check("index names an active key id for revocation checks", !string.IsNullOrEmpty(activeKeyId));
Check("every declared vector exists on disk",
    declared.Select(v => (string)v!["name"]!).OrderBy(n => n, StringComparer.Ordinal).SequenceEqual(onDisk),
    $"declared {declared.Count}, on disk {onDisk.Count}");

var vectors = onDisk
    .Select(n => JsonNode.Parse(File.ReadAllText(Path.Combine(vectorDir, n + ".json")))!.AsObject())
    .ToList();

var valid = vectors.Where(v => (bool)v["valid"]!).ToList();
var invalid = vectors.Where(v => !(bool)v["valid"]!).ToList();

Check("suite has valid and invalid vectors", valid.Count > 0 && invalid.Count > 0,
    $"{valid.Count} valid, {invalid.Count} invalid");

// ---------------------------------------------------------------- valid vectors

Console.WriteLine("\n[ valid vectors decrypt to the stated plaintext ]");

foreach (var v in valid)
{
    var name = (string)v["name"]!;
    try
    {
        var text = Open(v);
        var expected = Canonical(v["plaintext_json"]);
        var actual = Canonical(JsonNode.Parse(text));
        Check($"{name} round-trips", expected == actual, expected == actual ? null : $"got {Trim(actual)}");
    }
    catch (Exception ex)
    {
        Check($"{name} round-trips", false, ex.GetType().Name + ": " + ex.Message);
    }
}

// ---------------------------------------------------------------- AAD binding
//
// The point of putting header fields in the AAD is that a relay cannot rewrite
// routing metadata. Proving decryption succeeds does not prove that; only
// tampering and observing failure does.

Console.WriteLine("\n[ header fields are bound into the AEAD ]");

foreach (var v in valid)
{
    var name = (string)v["name"]!;
    var tampered = ((string)v["aad"]!).Replace("dir=e2p", "dir=p2e").Replace("dir=p2e|", "dir=e2p|");
    var mutatedAad = ((string)v["aad"]!) == tampered
        ? ((string)v["aad"]!) + "|x=1"   // fall back to appending, so the AAD always differs
        : tampered;

    bool rejected;
    try
    {
        OpenWith(v, mutatedAad);
        rejected = false;
    }
    catch (CryptographicException) { rejected = true; }

    Check($"{name} rejects a tampered AAD", rejected, "decryption succeeded under a modified header");
}

// ---------------------------------------------------------------- invalid vectors

Console.WriteLine("\n[ invalid vectors are rejected for the stated reason ]");

// Sequence tracking mirrors a real receiver: highest accepted seq per direction.
var highestSeq = new Dictionary<string, long>(StringComparer.Ordinal);
foreach (var v in valid)
{
    var env = v["envelope_json"]!.AsObject();
    var dir = (string)env["dir"]!;
    highestSeq[dir] = Math.Max(highestSeq.GetValueOrDefault(dir, 0), (long)env["seq"]!);
}

foreach (var v in invalid)
{
    var name = (string)v["name"]!;
    var expectedCode = (string?)v["expect_error"];
    var actualCode = Classify(v, highestSeq);
    Check($"{name} -> {expectedCode}", actualCode == expectedCode, $"got {actualCode ?? "accepted"}");
}

// ---------------------------------------------------------------- protocol rules

Console.WriteLine("\n[ protocol rules independent of any single vector ]");

Check("base64url decoder rejects padding", TryB64u("AAAA==", out _) == false);
Check("base64url decoder rejects standard-alphabet '+'", TryB64u("AA+A", out _) == false);
Check("base64url decoder rejects standard-alphabet '/'", TryB64u("AA/A", out _) == false);
Check("base64url decoder accepts unpadded input", TryB64u("AAAA", out var fourBytes) && fourBytes!.Length == 3);

foreach (var v in valid)
{
    var nonce = TryB64u((string)v["nonce_b64u"]!, out var nb) ? nb! : Array.Empty<byte>();
    Check($"{(string)v["name"]!} nonce is {NonceBytes} bytes", nonce.Length == NonceBytes, $"got {nonce.Length}");
}

Check("all valid-vector nonces are distinct",
    valid.Select(v => (string)v["nonce_b64u"]!).Distinct().Count() == valid.Count,
    "a repeated nonce under one key would break AES-GCM outright");

Check("ciphertexts carry a full 16-byte tag",
    valid.All(v => TryB64u((string)v["ciphertext_b64u"]!, out var ct) && ct!.Length >= TagBytes));

Check("no reserved L2 kind appears in the v1 shipping set",
    !reserved.Intersect(shipping, StringComparer.Ordinal).Any(),
    "overlap: " + string.Join(", ", reserved.Intersect(shipping, StringComparer.Ordinal)));
Check("'kill' is reserved, not shipping", reserved.Contains("kill") && !shipping.Contains("kill"));

// The invariant this whole program is built around: no payload kind may imply transmission.
var sendish = shipping.Where(k =>
    k.Contains("send", StringComparison.OrdinalIgnoreCase) ||
    k.Contains("submit", StringComparison.OrdinalIgnoreCase) ||
    k.Contains("transmit", StringComparison.OrdinalIgnoreCase)).ToList();
Check("no v1 payload kind implies a send path", sendish.Count == 0,
    sendish.Count == 0 ? null : "offending: " + string.Join(", ", sendish));

Check("envelope size limit is enforced above the crypto layer", MaxEnvelopeBytes == 1024 * 1024);

Console.WriteLine($"\n=== {passed} passed, {failed} failed ===");
return failed == 0 ? 0 : 1;

// ---------------------------------------------------------------- helpers

string Trim(string s) => s.Length <= 160 ? s : s[..160] + "…";

string Open(JsonObject v) => OpenWith(v, (string)v["aad"]!);

string OpenWith(JsonObject v, string aad)
{
    var key = Convert.FromHexString((string)v["key_hex"]!);
    if (!TryB64u((string)v["nonce_b64u"]!, out var nonce)) throw new FormatException("bad nonce encoding");
    if (!TryB64u((string)v["ciphertext_b64u"]!, out var sealed_)) throw new FormatException("bad ciphertext encoding");
    if (sealed_!.Length < TagBytes) throw new CryptographicException("ciphertext shorter than the tag");

    var body = sealed_.AsSpan(0, sealed_.Length - TagBytes);
    var tag = sealed_.AsSpan(sealed_.Length - TagBytes, TagBytes);
    var plaintext = new byte[body.Length];

    using var gcm = new AesGcm(key, TagBytes);
    gcm.Decrypt(nonce!, body, tag, plaintext, Encoding.ASCII.GetBytes(aad));
    return Encoding.UTF8.GetString(plaintext);
}

// Mirrors the order a real receiver applies checks: cheap header checks before crypto,
// crypto before payload interpretation. Rejecting for the wrong reason usually means a
// check fired earlier than intended and the real one is untested.
string? Classify(JsonObject v, Dictionary<string, long> highest)
{
    var env = v["envelope_json"]?.AsObject();

    if (env is null)
    {
        var synth = (int?)v["synth_ciphertext_len"];
        if (synth is not null && synth > MaxEnvelopeBytes) return "too_large";
        return null;
    }

    if ((int?)env["v"] != 1) return "version_unsupported";

    // Revocation is an explicit check, not a side effect of cryptography. A superseded
    // pairing whose derived key still decrypts is exactly what the tag check cannot catch.
    if ((string?)env["key_id"] != activeKeyId) return "key_unknown";

    var dir = (string)env["dir"]!;
    var seq = (long)env["seq"]!;

    if (!TryB64u((string)env["nonce"]!, out var nonce) || nonce!.Length != NonceBytes) return "decrypt_failed";
    if (!TryB64u((string)env["ciphertext"]!, out var sealed_)) return "decrypt_failed";
    if (sealed_!.Length > MaxEnvelopeBytes) return "too_large";

    if (seq <= highest.GetValueOrDefault(dir, 0)) return "replay_rejected";

    string text;
    try
    {
        // Reconstruct the AAD from the envelope as received. A tampered header therefore
        // produces a different AAD than the sender used, and the tag check fails.
        var aad = $"v={(int?)env["v"]}|pairing={(string?)env["pairing"]}|dir={dir}|seq={seq}"
                + $"|ts={(string?)env["ts"]}|key_id={(string?)env["key_id"]}";
        var key = Convert.FromHexString((string)v["key_hex"]!);
        var body = sealed_.AsSpan(0, sealed_.Length - TagBytes);
        var tag = sealed_.AsSpan(sealed_.Length - TagBytes, TagBytes);
        var plaintext = new byte[body.Length];
        using var gcm = new AesGcm(key, TagBytes);
        gcm.Decrypt(nonce, body, tag, plaintext, Encoding.ASCII.GetBytes(aad));
        text = Encoding.UTF8.GetString(plaintext);
    }
    catch (Exception)
    {
        return "decrypt_failed";
    }

    var kind = (string?)JsonNode.Parse(text)?["kind"];
    if (kind is null || !shipping.Contains(kind, StringComparer.Ordinal)) return "unknown_kind";

    return null;
}

// Strict, unpadded base64url. Deliberately rejects padded and standard-alphabet input:
// accepting both spellings would mean the vectors no longer pin one encoding.
bool TryB64u(string s, out byte[]? bytes)
{
    bytes = null;
    if (s.Length == 0 || s.Contains('=') || s.Contains('+') || s.Contains('/')) return false;

    var sb = new StringBuilder(s.Replace('-', '+').Replace('_', '/'));
    switch (sb.Length % 4)
    {
        case 2: sb.Append("=="); break;
        case 3: sb.Append('='); break;
        case 1: return false;
    }

    try { bytes = Convert.FromBase64String(sb.ToString()); return true; }
    catch (FormatException) { return false; }
}

// Order-independent comparison, so JS and .NET serializer differences cannot masquerade
// as a protocol mismatch.
string Canonical(JsonNode? node)
{
    switch (node)
    {
        case null: return "null";
        case JsonObject o:
            return "{" + string.Join(",", o.OrderBy(kv => kv.Key, StringComparer.Ordinal)
                .Select(kv => JsonSerializer.Serialize(kv.Key) + ":" + Canonical(kv.Value))) + "}";
        case JsonArray a:
            return "[" + string.Join(",", a.Select(Canonical)) + "]";
        default:
            return node.ToJsonString();
    }
}

static string? LocateVectorDirectory()
{
    var candidates = new List<string>();
    var cwd = Directory.GetCurrentDirectory();
    var probe = new DirectoryInfo(cwd);
    while (probe is not null) { candidates.Add(probe.FullName); probe = probe.Parent; }
    probe = new DirectoryInfo(AppContext.BaseDirectory);
    while (probe is not null) { candidates.Add(probe.FullName); probe = probe.Parent; }

    foreach (var root in candidates)
    {
        var path = Path.Combine(root, "docs", "sync-vectors", "v1");
        if (Directory.Exists(path) && File.Exists(Path.Combine(path, "index.json"))) return path;
    }
    return null;
}
