// Sync Protocol v1 conformance harness.
//
// P1: exercises the REAL shipping library (src/Sync) against the shared test vectors in
// docs/sync-vectors/v1/ -- the same files the Kotlin :core tests consume. The vectors are
// generated by Node (docs/sync-vectors/generate.mjs), so passing here is a genuine
// cross-implementation check: Node produced the bytes, the shipping C# consumes them.
//
// P0's version verified vectors with local helper crypto; those helpers are gone, which
// was always the plan ("when the real SyncPublisher lands in P1, this harness points at
// it instead").

using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using SeekerSvc.Sync;

int passed = 0, failed = 0;
void Check(string name, bool condition, string? detail = null)
{
    if (condition) { passed++; Console.WriteLine($"  PASS  {name}"); }
    else { failed++; Console.WriteLine($"  FAIL  {name}{(detail is null ? "" : $"  -- {detail}")}"); }
}

Console.WriteLine("=== CareerSeeker sync protocol v1 harness ===\n");

var vectorDir = LocateVectorDirectory();
if (vectorDir is null)
{
    Console.WriteLine("  FAIL  vector directory docs/sync-vectors/v1 not found");
    Console.WriteLine("\n=== 0 passed, 1 failed ===");
    return 1;
}
Console.WriteLine($"Vectors: {vectorDir}\n");

// ---------------------------------------------------------------- suite integrity

Console.WriteLine("[ vector suite integrity ]");

var index = JsonNode.Parse(File.ReadAllText(Path.Combine(vectorDir, "index.json")))!.AsObject();
var declared = index["vectors"]!.AsArray();
var activeKeyId = (string)index["active_key_id"]!;

Check("index declares AES-256-GCM", (string?)index["cipher"] == "AES-256-GCM");
Check("index suite matches the shipping suite", (string?)index["suite"] == Protocol.Suite,
    $"index={(string?)index["suite"]} code={Protocol.Suite}");
Check("index envelope limit matches the spec", (int?)index["max_envelope_bytes"] == Protocol.MaxEnvelopeBytes);
Check("index names an active key id for revocation checks", !string.IsNullOrEmpty(activeKeyId));

var onDisk = Directory.GetFiles(vectorDir, "*.json")
    .Select(Path.GetFileNameWithoutExtension)
    .Where(n => n != "index")
    .OrderBy(n => n, StringComparer.Ordinal)
    .ToList();
Check("every declared vector exists on disk",
    declared.Select(v => (string)v!["name"]!).OrderBy(n => n, StringComparer.Ordinal).SequenceEqual(onDisk),
    $"declared {declared.Count}, on disk {onDisk.Count}");

var vectors = onDisk
    .Select(n => JsonNode.Parse(File.ReadAllText(Path.Combine(vectorDir, n + ".json")))!.AsObject())
    .ToList();
var envelopeVectors = vectors.Where(v => (string)v["type"]! == "envelope").ToList();
var pairingVectors = vectors.Where(v => (string)v["type"]! == "pairing").ToList();

Check("suite has envelope and pairing vectors, valid and invalid",
    envelopeVectors.Any(v => (bool)v["valid"]!) && envelopeVectors.Any(v => !(bool)v["valid"]!)
    && pairingVectors.Any(v => (bool)v["valid"]!) && pairingVectors.Any(v => !(bool)v["valid"]!));

// ---------------------------------------------------------------- pairing derivation
//
// Done before the envelope work because the receiver needs the pairing's device key.

Console.WriteLine("\n[ pairing: section-5.2 derivation reproduces every vector value ]");

var pairingBasic = pairingVectors.Single(v => (string)v["name"]! == "pairing-basic");
var expected = pairingBasic["expected"]!.AsObject();
var secret = Convert.FromHexString(ToHex(pairingBasic["secret_b64u"]!));

using var engineKey = ImportEcdh((string)pairingBasic["engine"]!["d_hex"]!, (string)pairingBasic["engine"]!["pub_b64u"]!);
using var phoneKey = ImportEcdh((string)pairingBasic["phone"]!["d_hex"]!, (string)pairingBasic["phone"]!["pub_b64u"]!);
var enginePub = B64u((string)pairingBasic["engine"]!["pub_b64u"]!);
var phonePub = B64u((string)pairingBasic["phone"]!["pub_b64u"]!);
var devicePub = B64u((string)pairingBasic["device_sig"]!["pub_b64u"]!);

var ssEngineSide = PairingCrypto.ComputeSharedSecret(engineKey, phonePub);
var ssPhoneSide = PairingCrypto.ComputeSharedSecret(phoneKey, enginePub);
Check("ECDH shared secret matches the vector (engine side)",
    Convert.ToHexString(ssEngineSide).Equals((string)expected["ss_hex"]!, StringComparison.OrdinalIgnoreCase));
Check("ECDH is symmetric (phone side derives the same secret)",
    ssEngineSide.AsSpan().SequenceEqual(ssPhoneSide));

var keys = PairingCrypto.Derive(new[] { ssEngineSide }, secret);
Check("k_e2p matches", Convert.ToHexString(keys.KeyEngineToPhone).Equals((string)expected["k_e2p_hex"]!, StringComparison.OrdinalIgnoreCase));
Check("k_p2e matches", Convert.ToHexString(keys.KeyPhoneToEngine).Equals((string)expected["k_p2e_hex"]!, StringComparison.OrdinalIgnoreCase));
Check("relay token matches", keys.RelayToken == (string)expected["relay_token_b64u"]!);
Check("6-digit confirm code matches", keys.ConfirmCode == (string)expected["confirm"]!,
    $"derived {keys.ConfirmCode}, vector {(string)expected["confirm"]!}");
Check("provisional bootstrap token matches",
    PairingCrypto.ProvisionalRelayToken(secret) == (string)expected["provisional_token_b64u"]!);

var completion = pairingBasic["completion"]!.AsObject();
Check("completion AAD is reconstructed exactly",
    PairingCrypto.CompletionAad((string)index["pairing_id"]!, (string)pairingBasic["suite"]!, (string)pairingBasic["phone"]!["pub_b64u"]!)
        == (string)completion["aad"]!);

byte[]? completionPayload = null;
try
{
    completionPayload = EnvelopeCodec.Open(keys.KeyPhoneToEngine, B64u((string)completion["nonce_b64u"]!),
        (string)completion["aad"]!, B64u((string)completion["ciphertext_b64u"]!));
}
catch (CryptographicException) { /* fails the next check */ }
Check("completion opens under the derived k_p2e", completionPayload is not null);
Check("device signing key travels inside the completion ciphertext",
    completionPayload is not null
    && (string?)JsonNode.Parse(completionPayload)?["device_sig_pub"] == (string)pairingBasic["device_sig"]!["pub_b64u"]!);

// The MITM vector: relay swaps phone_pub for the attacker's. Deriving from the attacker
// key and opening MUST fail -- phone_pub is bound into the AAD *and* changes the key.
var mitm = pairingVectors.Single(v => (string)v["name"]! == "pairing-mitm-keyswap");
var attackerPub = B64u((string)mitm["phone"]!["pub_b64u"]!);
var mitmKeys = PairingCrypto.Derive(new[] { PairingCrypto.ComputeSharedSecret(engineKey, attackerPub) }, secret);
bool mitmRejected;
try
{
    EnvelopeCodec.Open(mitmKeys.KeyPhoneToEngine, B64u((string)mitm["completion"]!["nonce_b64u"]!),
        (string)mitm["completion"]!["aad"]!, B64u((string)mitm["completion"]!["ciphertext_b64u"]!));
    mitmRejected = false;
}
catch (CryptographicException) { mitmRejected = true; }
Check("pairing-mitm-keyswap: swapped phone_pub cannot decrypt the completion", mitmRejected,
    "a relay that substitutes keys must break the handshake, not hijack it");

// ---------------------------------------------------------------- valid envelope vectors

Console.WriteLine("\n[ valid envelope vectors decrypt and verify through src/Sync ]");

var validEnv = envelopeVectors.Where(v => (bool)v["valid"]!).ToList();
var invalidEnv = envelopeVectors.Where(v => !(bool)v["valid"]!).ToList();

foreach (var v in validEnv)
{
    var name = (string)v["name"]!;
    try
    {
        var text = Encoding.UTF8.GetString(EnvelopeCodec.Open(
            Convert.FromHexString((string)v["key_hex"]!), B64u((string)v["nonce_b64u"]!),
            (string)v["aad"]!, B64u((string)v["ciphertext_b64u"]!)));
        Check($"{name} round-trips", Canonical(JsonNode.Parse(text)) == Canonical(v["plaintext_json"]));
    }
    catch (Exception ex)
    {
        Check($"{name} round-trips", false, ex.GetType().Name);
    }

    if (v["envelope_json"]!["sig"] is not null)
    {
        var ciphertext = B64u((string)v["ciphertext_b64u"]!);
        var input = DeviceSignature.SigInput((string)v["aad"]!, (string)v["nonce_b64u"]!, ciphertext);
        Check($"{name} sig_input is reconstructed exactly", input == (string)v["sig_input"]!);
        Check($"{name} signature verifies under the device key",
            DeviceSignature.Verify(B64u((string)v["device_sig_pub_b64u"]!), input, B64u((string)v["envelope_json"]!["sig"]!)));
    }
}

Console.WriteLine("\n[ header fields are bound into the AEAD ]");

foreach (var v in validEnv)
{
    var aad = (string)v["aad"]!;
    var tampered = aad.Contains("dir=e2p") ? aad.Replace("dir=e2p", "dir=p2e") : aad.Replace("dir=p2e", "dir=e2p");
    bool rejected;
    try
    {
        EnvelopeCodec.Open(Convert.FromHexString((string)v["key_hex"]!), B64u((string)v["nonce_b64u"]!),
            tampered, B64u((string)v["ciphertext_b64u"]!));
        rejected = false;
    }
    catch (CryptographicException) { rejected = true; }
    Check($"{(string)v["name"]!} rejects a tampered AAD", rejected);
}

// ---------------------------------------------------------------- receiver state machine
//
// The REAL receiver (src/Sync EnvelopeReceiver) classifies every envelope vector. Valid
// vectors are fed first in sequence order -- the replay vector's notes require it -- and
// the receiver is constructed with the PAIRING's device key, which is what makes
// sig-by-revoked-key meaningful: that envelope verifies under the key it *names*, and
// must still be rejected because it is not the pairing's key.

Console.WriteLine("\n[ the shipping receiver classifies every vector correctly ]");

var receiver = new EnvelopeReceiver(activeKeyId, devicePub);
byte[] KeyFor(string dir) => dir == "e2p"
    ? Convert.FromHexString("a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90")
    : Convert.FromHexString("0f1e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0");

foreach (var v in validEnv.OrderBy(v => (long)v["envelope_json"]!["seq"]!))
{
    var result = receiver.Receive(ToReceived(v["envelope_json"]!.AsObject()), KeyFor);
    Check($"receiver accepts {(string)v["name"]!}", result.Accepted, result.Error?.ToWire());
}

foreach (var v in invalidEnv)
{
    var name = (string)v["name"]!;
    var expectedCode = (string)v["expect_error"]!;

    ReceiveResult result;
    if (v["envelope_json"] is null)
    {
        // invalid-oversized ships a synth length instead of a megabyte of literal 'A's.
        var synth = (int)v["synth_ciphertext_len"]!;
        var big = new ReceivedEnvelope(1, "p_7Fq2mXk9LtVbN3wR", "e2p", 999, "2026-06-11T14:02:11Z",
            activeKeyId, Base64Url.Encode(new byte[Protocol.NonceBytes]), Base64Url.Encode(new byte[synth]), null);
        result = receiver.Receive(big, KeyFor);
    }
    else
    {
        result = receiver.Receive(ToReceived(v["envelope_json"]!.AsObject()), KeyFor);
    }

    Check($"{name} -> {expectedCode}", result.Error?.ToWire() == expectedCode,
        $"got {result.Error?.ToWire() ?? "accepted"}");
}

Check("rejections never advanced the sequence tracker",
    receiver.HighestAccepted("e2p") == 4 && receiver.HighestAccepted("p2e") == 1,
    $"e2p={receiver.HighestAccepted("e2p")} p2e={receiver.HighestAccepted("p2e")}");

// ---------------------------------------------------------------- pairing manager
//
// Drives the engine's PairingManager through a full handshake using the pairing-basic
// vector's fixed keys, so the manager's orchestration (invite, provisional token,
// completion verification, secret burn) is checked against the same derivations the
// cross-repo vectors pin.

Console.WriteLine("\n[ engine PairingManager completes the handshake ]");

{
    var engineD = (string)pairingBasic["engine"]!["d_hex"]!;
    using var fixedEngineKey = ImportEcdh(engineD, (string)pairingBasic["engine"]!["pub_b64u"]!);
    var pairingId = (string)index["pairing_id"]!;
    using var mgr = new PairingManager("https://relay.careerseeker.app",
        engineKey: fixedEngineKey, oneTimeSecret: secret, pairingId: pairingId);

    var invite = mgr.CreateInvite();
    Check("invite carries the suite and engine pubkey",
        invite.Suite == Protocol.Suite && invite.EnginePub == (string)pairingBasic["engine"]!["pub_b64u"]!);
    Check("provisional token matches the derived value",
        mgr.ProvisionalRelayToken() == (string)expected["provisional_token_b64u"]!);

    // The phone's completion, reconstructed from the vector.
    var completionJson = JsonSerializer.Serialize(new
    {
        suite = Protocol.Suite,
        phone_pub = (string)pairingBasic["phone"]!["pub_b64u"]!,
        nonce = (string)completion["nonce_b64u"]!,
        ciphertext = (string)completion["ciphertext_b64u"]!,
    });

    var paired = mgr.CompletePairing(completionJson, out var err);
    Check("completion succeeds", paired is not null, err);
    Check("paired confirm code matches the vector", paired?.ConfirmCode == (string)expected["confirm"]!);
    Check("paired relay token matches the vector", paired?.RelayToken == (string)expected["relay_token_b64u"]!);
    Check("paired device key equals the one inside the completion",
        paired is not null && Base64Url.Encode(paired.DeviceSigPub) == (string)pairingBasic["device_sig"]!["pub_b64u"]!);

    // Single-use secret: a second completion, even the same valid one, is refused.
    var replay = mgr.CompletePairing(completionJson, out var replayErr);
    Check("secret is single-use (second completion refused)", replay is null, replayErr);

    // A key-swapped completion (the MITM vector) does not decrypt.
    var mitmJson = JsonSerializer.Serialize(new
    {
        suite = Protocol.Suite,
        phone_pub = (string)mitm["phone"]!["pub_b64u"]!,
        nonce = (string)mitm["completion"]!["nonce_b64u"]!,
        ciphertext = (string)mitm["completion"]!["ciphertext_b64u"]!,
    });
    using var mgr2 = new PairingManager("https://relay.careerseeker.app",
        engineKey: ImportEcdh(engineD, (string)pairingBasic["engine"]!["pub_b64u"]!),
        oneTimeSecret: secret, pairingId: pairingId);
    var mitmResult = mgr2.CompletePairing(mitmJson, out _);
    Check("PairingManager rejects a key-swapped completion", mitmResult is null);
}

// ---------------------------------------------------------------- protocol rules

Console.WriteLine("\n[ protocol rules independent of any single vector ]");

Check("base64url decoder rejects padding", !Base64Url.TryDecode("AAAA==", out _));
Check("base64url decoder rejects standard-alphabet '+'", !Base64Url.TryDecode("AA+A", out _));
Check("base64url decoder rejects standard-alphabet '/'", !Base64Url.TryDecode("AA/A", out _));
Check("base64url decoder accepts unpadded input", Base64Url.TryDecode("AAAA", out var three) && three.Length == 3);
Check("base64url round-trips", Base64Url.TryDecode(Base64Url.Encode(new byte[] { 1, 2, 3, 250 }), out var rt) && rt.SequenceEqual(new byte[] { 1, 2, 3, 250 }));

Check("all valid-vector nonces are distinct",
    validEnv.Select(v => (string)v["nonce_b64u"]!).Distinct().Count() == validEnv.Count);
Check("no reserved L2 kind appears in the v1 shipping set",
    !Protocol.ReservedL2Kinds.Intersect(Protocol.ShippingKinds, StringComparer.Ordinal).Any());
Check("'kill' is reserved, not shipping",
    Protocol.ReservedL2Kinds.Contains("kill") && !Protocol.ShippingKinds.Contains("kill"));
Check("state-changing kinds are a subset of shipping kinds",
    Protocol.StateChangingKinds.All(Protocol.ShippingKinds.Contains));
Check("no v1 payload kind implies a send path",
    !Protocol.ShippingKinds.Any(k => k.Contains("send") || k.Contains("submit") || k.Contains("transmit")));
Check("device key fingerprint is 16 lowercase hex chars",
    DeviceSignature.Fingerprint(devicePub) is { Length: 16 } fp && fp.All(c => "0123456789abcdef".Contains(c)));
Check("suite string names its post-quantum successor",
    Protocol.SuiteHybridReserved.Contains("mlkem") && Protocol.SuiteHybridReserved != Protocol.Suite);

Console.WriteLine($"\n=== {passed} passed, {failed} failed ===");
return failed == 0 ? 0 : 1;

// ---------------------------------------------------------------- helpers

static byte[] B64u(string s) => Base64Url.TryDecode(s, out var b)
    ? b : throw new FormatException($"vector value is not strict base64url: {s[..Math.Min(16, s.Length)]}…");

static string ToHex(JsonNode n) => Convert.ToHexString(Base64Url.TryDecode((string)n!, out var b) ? b : throw new FormatException());

static ReceivedEnvelope ToReceived(JsonObject env) => new(
    (int)env["v"]!, (string)env["pairing"]!, (string)env["dir"]!, (long)env["seq"]!,
    (string)env["ts"]!, (string)env["key_id"]!, (string)env["nonce"]!, (string)env["ciphertext"]!,
    env["sig"] is null ? null : (string)env["sig"]!);

static ECDiffieHellman ImportEcdh(string dHex, string pubB64u)
{
    var pub = Base64Url.TryDecode(pubB64u, out var p) ? p : throw new FormatException();
    return ECDiffieHellman.Create(new ECParameters
    {
        Curve = ECCurve.NamedCurves.nistP256,
        D = Convert.FromHexString(dHex),
        Q = new ECPoint { X = pub[1..33], Y = pub[33..] },
    });
}

static string Canonical(JsonNode? node) => node switch
{
    null => "null",
    JsonObject o => "{" + string.Join(",", o.OrderBy(kv => kv.Key, StringComparer.Ordinal)
        .Select(kv => JsonSerializer.Serialize(kv.Key) + ":" + Canonical(kv.Value))) + "}",
    JsonArray a => "[" + string.Join(",", a.Select(Canonical)) + "]",
    _ => node.ToJsonString(),
};

static string? LocateVectorDirectory()
{
    var candidates = new List<string>();
    var probe = new DirectoryInfo(Directory.GetCurrentDirectory());
    while (probe is not null) { candidates.Add(probe.FullName); probe = probe.Parent; }
    probe = new DirectoryInfo(AppContext.BaseDirectory);
    while (probe is not null) { candidates.Add(probe.FullName); probe = probe.Parent; }
    return candidates
        .Select(root => Path.Combine(root, "docs", "sync-vectors", "v1"))
        .FirstOrDefault(path => Directory.Exists(path) && File.Exists(Path.Combine(path, "index.json")));
}
